const express = require('express');
const zlib = require('zlib');
const { requireAuth, requireAdmin } = require('../middleware/authMiddleware');
const db = require('../db');
const { requireUnrestricted } = require('../services/scopeService');
const { LINUX_AGENT_VERSION, generateLinuxScript, generateLinuxInstaller } = require('../services/linuxAgentScript');

const router = express.Router();
const REGISTRATION_KEY = process.env.REGISTRATION_KEY || 'winserv-reg-key-change-me';
const AGENT_VERSION = '2.27';

function generateUniversalScript(serverUrl, regKey) {
  return [
    '# WinServ Monitoring Agent v' + AGENT_VERSION,
    '# ====================================================================',
    '# Auto-registers on first run. One script for all servers.',
    '# Save to C:\\winserv-agent\\agent.ps1 and schedule:',
    '#   schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo 1 /tr "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1" /f',
    '# ====================================================================',
    'try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}',
    '# TLS: enable the strongest protocols THIS .NET actually knows. Naming Tls13',
    '# directly throws on .NET < 4.8, which aborted the whole assignment and left',
    '# the default (TLS 1.0) — HTTPS then fails outright. Probe each value instead.',
    'try {',
    '  $sp = [System.Net.ServicePointManager]::SecurityProtocol',
    '  foreach ($n in @(\'Tls12\', \'Tls13\')) {',
    '    try { $sp = $sp -bor [Enum]::Parse([System.Net.SecurityProtocolType], $n) } catch {}',
    '  }',
    '  [System.Net.ServicePointManager]::SecurityProtocol = $sp',
    '} catch {}',
    '',
    '$ErrorActionPreference = "Continue"',
    '# Rendering a progress bar makes web transfers ~5x slower and nothing shows it.',
    '$ProgressPreference = "SilentlyContinue"',
    '$AgentVersion = "' + AGENT_VERSION + '"',
    '$ServerUrl = "' + serverUrl + '"',
    '$MetricsUrl = "$ServerUrl/api/metrics"',
    '$EventsUrl = "$ServerUrl/api/events"',
    '$SecurityUrl = "$ServerUrl/api/security"',
    '$HealthUrl = "$ServerUrl/api/health-report"',
    '$InventoryUrl = "$ServerUrl/api/inventory-report"',
    '$ProcessUrl = "$ServerUrl/api/process-report"',
    '$RegKey = "' + regKey + '"',
    '$ConfigFile = "$env:ProgramData\\WinServAgent\\config.json"',
    '$LogFile = "$env:ProgramData\\WinServAgent\\agent.log"',
    '',
    '# Heartbeat: write timestamp to prove script started',
    'try { Get-Date -Format \'yyyy-MM-dd HH:mm:ss\' | Out-File "C:\\winserv-agent\\heartbeat.txt" -Encoding UTF8 } catch {}',
    '',
    'function Write-Log($msg) {',
    '  $dir = Split-Path $LogFile -Parent',
    '  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }',
    '  $ts = Get-Date -Format \'yyyy-MM-dd HH:mm:ss\'',
    '  "$ts $msg" | Out-File $LogFile -Append -Encoding UTF8',
    '}',
    '',
    '$PSVer = try { $PSVersionTable.PSVersion } catch { $null }',
    'Write-Log "Agent v$AgentVersion started (PowerShell $PSVer, TLS $([System.Net.ServicePointManager]::SecurityProtocol))"',
    '# Fail loudly instead of dying silently: this agent needs PS 3.0+ for',
    '# Get-CimInstance / ConvertTo-Json / Invoke-RestMethod.',
    'if ($PSVer -and $PSVer.Major -lt 3) {',
    '  Write-Log "FATAL: PowerShell $PSVer is too old. Install WMF 3.0+ (and .NET 4.5+ for TLS 1.2), then this agent will work. Nothing will be reported until then."',
    '  exit 1',
    '}',
    '',
    '# Run budget. The scheduled task will not start a second instance while one is',
    '# running, so a slow collector (a hung WMI perf class on a loaded DC can block',
    '# for many minutes) silently stops metrics and the server looks OFFLINE.',
    '# Heavy collectors are therefore skipped once the run exceeds its budget —',
    '# they simply run on a later pass, while the metrics cadence is never lost.',
    '$RunSw = [System.Diagnostics.Stopwatch]::StartNew()',
    'function Test-Budget($sec) { return ($RunSw.Elapsed.TotalSeconds -lt $sec) }',
    'Set-TaskTimeLimit',
    '',
    '$FullHostname = try { [System.Net.Dns]::GetHostEntry(\'\').HostName } catch { "$env:COMPUTERNAME.$env:USERDNSDOMAIN" }',
    'if (-not $FullHostname -or $FullHostname -notmatch \'\\.\') { $FullHostname = "$env:COMPUTERNAME.$env:USERDNSDOMAIN" }',
    '',
    'function Get-SystemMetrics {',
    '  $cpu = (Get-CimInstance Win32_Processor -OperationTimeoutSec 10 | Measure-Object -Property LoadPercentage -Average).Average',
    '  $os = Get-CimInstance Win32_OperatingSystem -OperationTimeoutSec 10',
    '  $memTotalMB = [math]::Round($os.TotalVisibleMemorySize / 1024, 0)',
    '  $memFreeMB = [math]::Round($os.FreePhysicalMemory / 1024, 0)',
    '  $memUsedMB = $memTotalMB - $memFreeMB',
    '  $disks = Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3" -OperationTimeoutSec 10 -ErrorAction SilentlyContinue',
    '  $diskPerf = @{}',
    '  try {',
    '    Get-CimInstance Win32_PerfFormattedData_PerfDisk_LogicalDisk -OperationTimeoutSec 10 -ErrorAction Stop | Where-Object { $_.Name -match \'^[A-Z]:$\' } | ForEach-Object {',
    '      $diskPerf[$_.Name] = @{',
    '        read_bytes_sec = [math]::Round($_.DiskReadBytesPerSec, 0)',
    '        write_bytes_sec = [math]::Round($_.DiskWriteBytesPerSec, 0)',
    '        disk_time_pct = [math]::Round($_.PercentDiskTime, 1)',
    '        queue_length = [math]::Round($_.CurrentDiskQueueLength, 1)',
    '      }',
    '    }',
    '  } catch {}',
    '  $diskArray = @()',
    '  $diskTotalGB = 0; $diskUsedGB = 0; $diskFreeGB = 0',
    '  foreach ($d in $disks) {',
    '    $sizeGB = [math]::Round($d.Size / 1GB, 1)',
    '    $freeGB = [math]::Round($d.FreeSpace / 1GB, 1)',
    '    $usedGB = [math]::Round(($d.Size - $d.FreeSpace) / 1GB, 1)',
    '    $diskTotalGB += $sizeGB',
    '    $diskFreeGB += $freeGB',
    '    $diskUsedGB += $usedGB',
    '    $perf = $diskPerf[$d.DeviceID]',
    '    $diskEntry = @{ drive = $d.DeviceID; total_gb = $sizeGB; used_gb = $usedGB; free_gb = $freeGB }',
    '    if ($perf) {',
    '      $diskEntry.read_bytes_sec = $perf.read_bytes_sec',
    '      $diskEntry.write_bytes_sec = $perf.write_bytes_sec',
    '      $diskEntry.disk_time_pct = $perf.disk_time_pct',
    '      $diskEntry.queue_length = $perf.queue_length',
    '    }',
    '    $diskArray += $diskEntry',
    '  }',
    '  $uptime = [math]::Round(((Get-Date) - $os.LastBootUpTime).TotalSeconds, 0)',
    '  return @{',
    '    cpu_usage = $cpu',
    '    memory_total_mb = $memTotalMB',
    '    memory_used_mb = $memUsedMB',
    '    disk_total_gb = $diskTotalGB',
    '    disk_used_gb = $diskUsedGB',
    '    disk_free_gb = $diskFreeGB',
    '    disks = $diskArray',
    '    uptime_seconds = $uptime',
    '  }',
    '}',
    '',
    'function Get-CriticalEvents {',
    '  $since = (Get-Date).AddMinutes(-30)',
    '  $events = $null',
    '  try {',
    '    $events = Invoke-Bounded { param($s) Get-WinEvent -FilterHashtable @{LogName="System";Level=1,2,3;StartTime=$s} -MaxEvents 200 -ErrorAction Stop } 25 @($since)',
    '    if ($null -eq $events) { throw "event query timed out" }',
    '  } catch {',
    '    try {',
    '      $events = Get-EventLog -LogName System -EntryType Error,Warning -After $since -Newest 200 -ErrorAction Stop',
    '    } catch {',
    '      Write-Log "EventLog: cannot read System log"',
    '      return @()',
    '    }',
    '  }',
    '  if (-not $events) { return @() }',
    '  $result = @()',
    '  foreach ($e in $events) {',
    '    $source = if ($e.ProviderName) { $e.ProviderName } else { $e.Source }',
    '    $eid = if ($e.Id) { $e.Id } else { $e.EventID }',
    '    $lvlNum = if ($e.Level) { $e.Level } else { 2 }',
    '    if ($lvlNum -le 1) { $lvl = \'Critical\' }',
    '    elseif ($lvlNum -le 2) { $lvl = \'Error\' }',
    '    elseif ($lvlNum -le 3) { $lvl = \'Warning\' }',
    '    else { $lvl = \'Information\' }',
    '    try {',
    '      $msg = if ($e.Message) { if ($e.Message.Length -gt 2000) { $e.Message.Substring(0, 2000) } else { $e.Message } } else { \'\' }',
    '    } catch { $msg = \'\' }',
    '    $time = if ($e.TimeCreated) { $e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\') } else { $e.TimeGenerated.ToString(\'yyyy-MM-ddTHH:mm:ss\') }',
    '    $result += @{source=$source;event_id=$eid;level=$lvl;message=$msg;recorded_at=$time}',
    '  }',
    '  Write-Log "Events collected: $($result.Count)"',
    '  return $result',
    '}',
    '',
    'function Get-TriggeredEvents($triggers) {',
    '  # Collect user-configured Event IDs regardless of level, from their logs.',
    '  if (-not $triggers) { return @() }',
    '  $since = (Get-Date).AddMinutes(-30)',
    '  $byLog = @{}',
    '  foreach ($t in $triggers) {',
    '    $log = if ($t.log_name) { "$($t.log_name)" } else { "System" }',
    '    if (-not $byLog.ContainsKey($log)) { $byLog[$log] = @() }',
    '    $byLog[$log] += [int]$t.event_id',
    '  }',
    '  $result = @()',
    '  foreach ($log in $byLog.Keys) {',
    '    $ids = @($byLog[$log] | Select-Object -Unique)',
    '    try {',
    '      $evs = Get-WinEvent -FilterHashtable @{LogName=$log;Id=$ids;StartTime=$since} -MaxEvents 100 -ErrorAction Stop',
    '      foreach ($e in $evs) {',
    '        $src = if ($e.ProviderName) { $e.ProviderName } else { "" }',
    '        $lvlNum = if ($e.Level) { $e.Level } else { 4 }',
    '        if ($lvlNum -le 1) { $lvl = "Critical" } elseif ($lvlNum -le 2) { $lvl = "Error" } elseif ($lvlNum -le 3) { $lvl = "Warning" } else { $lvl = "Information" }',
    '        $m = ""; try { if ($e.Message) { $m = if ($e.Message.Length -gt 2000) { $e.Message.Substring(0,2000) } else { $e.Message } } } catch {}',
    '        $tm = if ($e.TimeCreated) { $e.TimeCreated.ToString("yyyy-MM-ddTHH:mm:ss") } else { (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss") }',
    '        $result += @{source=$src;event_id=$e.Id;level=$lvl;message=$m;recorded_at=$tm}',
    '      }',
    '    } catch {}',
    '  }',
    '  return $result',
    '}',
    '',
    'function Save-Token {',
    '  # Persists token + applied schedule interval + last heavy-collection times.',
    '  try {',
    '    $dir = Split-Path $ConfigFile -Parent',
    '    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }',
    '    $o = @{ token = $Token }',
    '    if ($AppliedInterval) { $o.interval = $AppliedInterval }',
    '    if ($LastSec) { $o.sec_at = $LastSec.ToString("o") }',
    '    if ($LastHealth) { $o.health_at = $LastHealth.ToString("o") }',
    '    if ($LastInv) { $o.inv_at = $LastInv.ToString("o") }',
    '    if ($LastProc) { $o.proc_at = $LastProc.ToString("o") }',
    '    if ($LastUpd) { $o.upd_at = $LastUpd.ToString("o") }',
    '    $o.upd_err = "$LastUpdErr"',
    '    $o | ConvertTo-Json | Set-Content $ConfigFile -Force',
    '  } catch { Write-Log "Save-Token error: $_" }',
    '}',
    '',
    'function Send-Body($url, $body) {',
    '  # Deliberately a DIRECT call, not wrapped in Invoke-Bounded. Routing this',
    '  # through a runspace looked like sound hardening, but it is the one call',
    '  # every host depends on, and older PowerShell did not survive it: four',
    '  # Server 2012 R2 machines that had held 100% coverage for a week went',
    '  # completely silent within minutes of receiving that build. Anything',
    '  # changed here reaches the entire fleet at once and cannot be verified on',
    '  # 2019 alone, so this stays as plain as possible.',
    '  try {',
    '    return Invoke-RestMethod -Uri $url -Method POST -Body $body -ContentType "application/json; charset=utf-8" -TimeoutSec 15',
    '  } catch {',
    '    Write-Log "Send-Body $url : $_"',
    '    return $null',
    '  }',
    '}',
    '',
    'function Install-AgentScript($target, $content) {',
    '  # Replacing the currently-running script is the step that was failing',
    '  # silently: it had no try/catch, so a read-only file or a denied write left',
    '  # the agent on the old version with nothing reported anywhere. Several',
    '  # strategies are tried and the result is VERIFIED by reading the file back,',
    '  # because "no exception" is not proof that the bytes landed.',
    '  $script:UpdateError = ""',
    '  $tmp = "$target.new"',
    '  try {',
    '    if (Test-Path $target) { try { Set-ItemProperty -Path $target -Name IsReadOnly -Value $false -ErrorAction SilentlyContinue } catch {} }',
    '    [System.IO.File]::WriteAllText($tmp, $content, (New-Object System.Text.UTF8Encoding($false)))',
    '  } catch {',
    '    $script:UpdateError = "cannot write $($tmp): $($_.Exception.Message)"',
    '    return $false',
    '  }',
    '  $errs = @()',
    '  foreach ($how in @("move", "copy", "iocopy", "direct")) {',
    '    try {',
    '      if     ($how -eq "move")   { Move-Item -Path $tmp -Destination $target -Force -ErrorAction Stop }',
    '      elseif ($how -eq "copy")   { Copy-Item -Path $tmp -Destination $target -Force -ErrorAction Stop }',
    '      elseif ($how -eq "iocopy") { [System.IO.File]::Copy($tmp, $target, $true) }',
    '      else                       { [System.IO.File]::WriteAllText($target, $content, (New-Object System.Text.UTF8Encoding($false))) }',
    '      $onDisk = ""',
    '      try { $onDisk = [System.IO.File]::ReadAllText($target) } catch {}',
    '      if ($onDisk -and $onDisk.Length -ge ($content.Length - 8)) {',
    '        Remove-Item $tmp -Force -ErrorAction SilentlyContinue',
    '        Write-Log "Agent script replaced via $($how)"',
    '        return $true',
    '      }',
    '      $errs += "$($how): wrote but file is $($onDisk.Length) chars"',
    '    } catch { $errs += "$($how): $($_.Exception.Message)" }',
    '  }',
    '  Remove-Item $tmp -Force -ErrorAction SilentlyContinue',
    '  $script:UpdateError = ($errs -join " | ")',
    '  return $false',
    '}',
    '',
    'function Get-UpdateScript {',
    '  # Robust download of the latest agent script. Corporate egress (TLS',
    '  # inspection / MTU) can stall a ~25KB GET while small POSTs pass, so we',
    '  # retry with a fresh connection each time, stream to disk, and allow a',
    '  # generous per-attempt timeout.',
    '  # HttpWebRequest, not Invoke-WebRequest: the latter renders a progress bar',
    '  # (measured 5x slower on the same file), performs WPAD proxy discovery that',
    '  # can stall for SYSTEM, and gives no control over the read timeout - only',
    '  # over connection setup, so a trickling transfer ran far past -TimeoutSec.',
    '  # Attempt 2 goes through the system proxy in case direct egress is blocked.',
    '  # The reason for a failure is kept so force_update can report it verbatim',
    '  # instead of a guess.',
    '  $script:UpdateError = "no attempt made"',
    '  for ($try = 1; $try -le 3; $try++) {',
    '    $sw = [System.Diagnostics.Stopwatch]::StartNew()',
    '    try {',
    '      $req = [System.Net.HttpWebRequest]::Create("$ServerUrl/api/agent/self-update?token=$Token")',
    '      $req.Method = "GET"',
    '      $req.Timeout = 30000',
    '      $req.ReadWriteTimeout = 30000',
    '      $req.UserAgent = "WinServ-Agent/$AgentVersion"',
    '      if ($try -eq 2) { $req.Proxy = [System.Net.WebRequest]::DefaultWebProxy } else { $req.Proxy = $null }',
    '      try { $req.AutomaticDecompression = [System.Net.DecompressionMethods]::GZip -bor [System.Net.DecompressionMethods]::Deflate } catch {}',
    '      $resp = $req.GetResponse()',
    '      $sr = New-Object System.IO.StreamReader($resp.GetResponseStream())',
    '      $content = $sr.ReadToEnd()',
    '      $sr.Close(); $resp.Close()',
    '      if ($content -and $content.Length -gt 1000 -and $content -match "WinServ Monitoring Agent") {',
    '        Write-Log "Update downloaded: $($content.Length) chars in $($sw.ElapsedMilliseconds)ms (attempt $($try))"',
    '        return $content',
    '      }',
    '      $script:UpdateError = "bad payload, $($content.Length) chars in $($sw.ElapsedMilliseconds)ms"',
    '    } catch {',
    '      $script:UpdateError = "$($_.Exception.Message) after $($sw.ElapsedMilliseconds)ms"',
    '    }',
    '    Write-Log "Update attempt $($try) failed: $($script:UpdateError)"',
    '    Start-Sleep -Seconds 3',
    '  }',
    '  return $null',
    '}',
    '',
    'function Get-SecurityEvents {',
    '  # 4625 failed logons (brute-force signal) + 4624 RDP successes (type 10).',
    '  $since = (Get-Date).AddMinutes(-30)',
    '  try {',
    '    $events = Invoke-Bounded { param($s) Get-WinEvent -FilterHashtable @{LogName="Security";Id=4624,4625;StartTime=$s} -MaxEvents 150 -ErrorAction Stop } 25 @($since)',
    '    if ($null -eq $events) { return @() }',
    '  } catch { return @() }',
    '  if (-not $events) { return @() }',
    '  $result = @()',
    '  foreach ($e in $events) {',
    '    try {',
    '      $x = [xml]$e.ToXml(); $d = @{}',
    '      foreach ($n in $x.Event.EventData.Data) { $d[$n.Name] = $n."#text" }',
    '      $lt = "$($d[\'LogonType\'])"',
    '      $ip = "$($d[\'IpAddress\'])"',
    '      $acct = "$($d[\'TargetUserName\'])"',
    '      if ($e.Id -eq 4625) {',
    '        if (-not $ip -or $ip -eq \'-\' -or $ip -eq \'::1\' -or $ip -eq \'127.0.0.1\') { continue }',
    '        $result += @{event=\'fail\';account=$acct;ip=$ip;logon_type=$lt;recorded_at=$e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\')}',
    '      } else {',
    '        if ($lt -ne \'10\') { continue }',
    '        $result += @{event=\'success\';account=$acct;ip=$ip;logon_type=$lt;recorded_at=$e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\')}',
    '      }',
    '    } catch {}',
    '  }',
    '  return $result',
    '}',
    '',
    'function Get-HealthInfo {',
    '  $h = @{ pending_reboot = $false; services = @(); certs = @(); tasks = @() }',
    '  try {',
    '    Invoke-Bounded { Get-CimInstance Win32_Service -Filter "StartMode=`\'Auto`\' AND State=`\'Stopped`\'" -OperationTimeoutSec 15 -ErrorAction Stop } 20 | Where-Object { $_ } | ForEach-Object {',
    '      $h.services += @{ name = $_.Name; display = $_.DisplayName }',
    '    }',
    '  } catch {}',
    '  try {',
    '    if (Test-Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Component Based Servicing\\RebootPending") { $h.pending_reboot = $true }',
    '    if (Test-Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired") { $h.pending_reboot = $true }',
    '    $pfr = (Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue)',
    '    if ($pfr -and $pfr.PendingFileRenameOperations) { $h.pending_reboot = $true }',
    '  } catch {}',
    '  try {',
    '    $limit = (Get-Date).AddDays(30)',
    '    Get-ChildItem Cert:\\LocalMachine\\My -ErrorAction Stop | Where-Object { $_.NotAfter -lt $limit -and $_.NotAfter -gt (Get-Date).AddDays(-1) } | ForEach-Object {',
    '      $h.certs += @{ subject = $_.Subject; expires = $_.NotAfter.ToString(\'yyyy-MM-dd\') }',
    '    }',
    '  } catch {}',
    '  try {',
    '    Invoke-Bounded { Get-ScheduledTask -ErrorAction Stop } 25 | Where-Object { $_ -and $_.State -ne "Disabled" } | ForEach-Object {',
    '      $info = $_ | Get-ScheduledTaskInfo -ErrorAction SilentlyContinue',
    '      if ($info -and $info.LastTaskResult -ne 0 -and $info.LastTaskResult -ne 267009 -and $info.LastTaskResult -ne 267011 -and $info.LastRunTime -gt (Get-Date).AddDays(-2)) {',
    '        $h.tasks += @{ name = $_.TaskName; result = $info.LastTaskResult }',
    '      }',
    '    }',
    '  } catch {}',
    '  return $h',
    '}',
    '',
    'function Get-Inventory {',
    '  # Hardware snapshot + installed software (from Uninstall registry keys).',
    '  $inv = @{ hardware = @{}; software = @(); patches = @{} }',
    '  try {',
    '    $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue',
    '    $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue',
    '    $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '    $cpu = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1',
    '    $cores = (Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property NumberOfCores -Sum).Sum',
    '    $logical = (Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum',
    '    $ramGb = 0; if ($cs -and $cs.TotalPhysicalMemory) { $ramGb = [math]::Round($cs.TotalPhysicalMemory / 1GB, 1) }',
    '    $inv.hardware = @{',
    '      manufacturer = "$($cs.Manufacturer)"',
    '      model = "$($cs.Model)"',
    '      serial = "$($bios.SerialNumber)"',
    '      os_caption = "$($os.Caption)"',
    '      os_version = "$($os.Version)"',
    '      os_build = "$($os.BuildNumber)"',
    '      cpu = ("$($cpu.Name)").Trim()',
    '      cpu_cores = [int]$cores',
    '      cpu_logical = [int]$logical',
    '      ram_gb = $ramGb',
    '      disks = @()',
    '    }',
    '    Get-CimInstance Win32_DiskDrive -ErrorAction SilentlyContinue | ForEach-Object {',
    '      $szGb = 0; if ($_.Size) { $szGb = [math]::Round($_.Size / 1GB, 1) }',
    '      $inv.hardware.disks += @{ model = "$($_.Model)"; size_gb = $szGb; media = "$($_.MediaType)" }',
    '    }',
    '  } catch { Write-Log "Inventory hardware error: $_" }',
    '  try {',
    '    $paths = @("HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*", "HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*")',
    '    $seen = @{}',
    '    foreach ($p in $paths) {',
    '      Get-ItemProperty $p -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -and -not $_.SystemComponent -and -not $_.ReleaseType -and -not $_.ParentKeyName } | ForEach-Object {',
    '        $k = "$($_.DisplayName)|$($_.DisplayVersion)"',
    '        if (-not $seen.ContainsKey($k)) {',
    '          $seen[$k] = $true',
    '          $inv.software += @{ name = "$($_.DisplayName)"; version = "$($_.DisplayVersion)"; publisher = "$($_.Publisher)"; installed_on = "$($_.InstallDate)" }',
    '        }',
    '      }',
    '    }',
    '  } catch { Write-Log "Inventory software error: $_" }',
    '  try {',
    '    # Patch status from Get-HotFix (local, no Windows Update network call).',
    '    $hf = Invoke-Bounded { Get-HotFix -ErrorAction Stop } 40 | Where-Object { $_ -and $_.HotFixID -match "KB" }',
    '    $last = ($hf | Where-Object { $_.InstalledOn } | Sort-Object InstalledOn -Descending | Select-Object -First 1).InstalledOn',
    '    $lastStr = ""; if ($last) { $lastStr = $last.ToString("yyyy-MM-dd") }',
    '    $inv.patches = @{ last_installed = $lastStr; hotfixes = @() }',
    '    $hf | Sort-Object InstalledOn -Descending | Select-Object -First 20 | ForEach-Object {',
    '      $d = ""; if ($_.InstalledOn) { $d = $_.InstalledOn.ToString("yyyy-MM-dd") }',
    '      $inv.patches.hotfixes += @{ id = "$($_.HotFixID)"; installed_on = $d }',
    '    }',
    '  } catch { Write-Log "Inventory patches error: $_" }',
    '  return $inv',
    '}',
    '',
    'function Set-TaskTimeLimit {',
    '  # Belt and braces: ask Task Scheduler itself to kill a run that overruns.',
    '  # Every in-script timeout depends on our code getting control back, and a',
    '  # wedged provider never returns control. Windows killing the process is the',
    '  # only guarantee, and the next tick then starts a clean run. Done over COM',
    '  # so it also works on Server 2008, which has no ScheduledTasks module.',
    '  try {',
    '    $svc = New-Object -ComObject Schedule.Service',
    '    $svc.Connect()',
    '    $folder = $svc.GetFolder("\\")',
    '    $task = $folder.GetTask("WinServAgent")',
    '    $def = $task.Definition',
    '    if ($def.Settings.ExecutionTimeLimit -ne "PT5M") {',
    '      $def.Settings.ExecutionTimeLimit = "PT5M"',
    '      # 4 = TASK_UPDATE, 3 = TASK_LOGON_SERVICE_ACCOUNT',
    '      [void]$folder.RegisterTaskDefinition("WinServAgent", $def, 4, $null, $null, 3)',
    '      Write-Log "Scheduled task execution limit set to 5 minutes"',
    '    }',
    '  } catch {}',
    '}',
    '',
    'function Write-BoundedError($m) {',
    '  # An empty event log is a normal state, not a failure worth reporting.',
    '  if ("$m" -match "No events were found") { return }',
    '  Write-Log "Bounded call error: $m"',
    '}',
    '',
    'function Invoke-Bounded($sb, $seconds, $argv) {',
    '  # Hard wall-clock cap for a single call. Needed because WMI and the',
    '  # Defender cmdlets can hang past any -OperationTimeoutSec, and the',
    '  # scheduled task will not start a second instance while one is stuck, so',
    '  # one wedged query silently ends all monitoring for that host until it is',
    '  # rebooted. A runspace can be abandoned; an inline call cannot.',
    '  #',
    '  # Pass anything the scriptblock needs through $argv. The block runs in a',
    '  # FRESH runspace and does NOT inherit caller variables, so a captured',
    '  # $var arrives as $null - which is how the event collectors were quietly',
    '  # broken for a whole release. Use { param($x) ... } together with $argv.',
    '  $ps = [PowerShell]::Create()',
    '  [void]$ps.AddScript($sb)',
    '  if ($argv) { foreach ($a in @($argv)) { [void]$ps.AddArgument($a) } }',
    '  try {',
    '    $h = $ps.BeginInvoke()',
    '    if ($h.AsyncWaitHandle.WaitOne([TimeSpan]::FromSeconds($seconds))) {',
    '      $out = $null',
    '      try { $out = $ps.EndInvoke($h) }',
    '      catch { Write-BoundedError "$($_.Exception.Message)" }',
    '      # A failing cmdlet usually does NOT make EndInvoke throw - the record',
    '      # lands in the runspace error stream instead. That is exactly how a',
    '      # broken collector stayed invisible for a whole release, so the',
    '      # stream is inspected explicitly rather than trusted to raise.',
    '      try {',
    '        if ($ps.HadErrors) {',
    '          foreach ($er in $ps.Streams.Error) { Write-BoundedError "$($er.Exception.Message)" }',
    '        }',
    '      } catch {}',
    '      try { $ps.Dispose() } catch {}',
    '      return $out',
    '    }',
    '    # Timed out. Stop asynchronously and do NOT dispose: when the worker is',
    '    # blocked inside a native provider, Stop() and Dispose() block with it,',
    '    # reintroducing the very hang this function exists to prevent. The',
    '    # runspace is abandoned and dies with the process on the next tick.',
    '    Write-Log "Bounded call exceeded $seconds s - abandoned"',
    '    try { [void]$ps.BeginStop($null, $null) } catch {}',
    '    return $null',
    '  } catch { return $null }',
    '}',
    '',
    'function ConvertTo-AgeDays($v) {',
    '  # Defender reports "never scanned" as UInt32 max, which overflows [int] and',
    '  # would abort the whole collector. Anything absurd becomes $null instead.',
    '  $n = $v -as [long]',
    '  if ($null -eq $n -or $n -lt 0 -or $n -gt 36500) { return $null }',
    '  return [int]$n',
    '}',
    '',
    'function Get-DefenderStatus {',
    '  # Posture of Microsoft Defender plus any detections it recorded. If the',
    '  # cmdlets are missing (feature removed, or a third-party AV owns the box)',
    '  # we report available=false rather than pretending protection is off.',
    '  $d = @{ available = $false; threats = @() }',
    '  if (-not (Get-Command Get-MpComputerStatus -ErrorAction SilentlyContinue)) { return $d }',
    '  try {',
    '    $s = Invoke-Bounded { Get-MpComputerStatus -ErrorAction Stop } 25',
    '    if (-not $s) { $d.stalled = $true; return $d }',
    '    $d.available = $true',
    '    $d.av_enabled = [bool]$s.AntivirusEnabled',
    '    $d.realtime_enabled = [bool]$s.RealTimeProtectionEnabled',
    '    $d.behavior_monitor = [bool]$s.BehaviorMonitorEnabled',
    '    $d.tamper_protected = [bool]$s.IsTamperProtected',
    '    $d.signature_age_days = ConvertTo-AgeDays $s.AntivirusSignatureAge',
    '    $d.quick_scan_age_days = ConvertTo-AgeDays $s.QuickScanAge',
    '    $d.full_scan_age_days = ConvertTo-AgeDays $s.FullScanAge',
    '    $d.engine_version = "$($s.AMEngineVersion)"',
    '    $d.product_version = "$($s.AMProductVersion)"',
    '    if ($s.AntivirusSignatureLastUpdated) { $d.signature_updated = $s.AntivirusSignatureLastUpdated.ToString("yyyy-MM-ddTHH:mm:ss") }',
    '  } catch { return $d }',
    '  try {',
    '    # Map ThreatID -> name, then report what was detected in the last week.',
    '    $names = @{}',
    '    Invoke-Bounded { Get-MpThreat -ErrorAction SilentlyContinue } 20 | ForEach-Object { if ($_) { $names["$($_.ThreatID)"] = "$($_.ThreatName)" } }',
    '    $since = (Get-Date).AddDays(-7)',
    '    Invoke-Bounded { Get-MpThreatDetection -ErrorAction SilentlyContinue } 25 |',
    '      Where-Object { $_.InitialDetectionTime -and $_.InitialDetectionTime -gt $since } |',
    '      Sort-Object InitialDetectionTime -Descending | Select-Object -First 25 | ForEach-Object {',
    '        $nm = "$($names["$($_.ThreatID)"])"; if (-not $nm) { $nm = "ThreatID $($_.ThreatID)" }',
    '        $d.threats += @{',
    '          name = $nm',
    '          detected_at = $_.InitialDetectionTime.ToString("yyyy-MM-ddTHH:mm:ss")',
    '          resource = ("$($_.Resources -join \'; \')")',
    '          action_success = [bool]$_.ActionSuccess',
    '        }',
    '      }',
    '  } catch {}',
    '  # Server SKUs have no SecurityCenter2, so this is best-effort only.',
    '  try {',
    '    $av = Invoke-Bounded { Get-CimInstance -Namespace root\\SecurityCenter2 -ClassName AntiVirusProduct -ErrorAction Stop } 15 |',
    '          Where-Object { $_.displayName -and $_.displayName -notmatch \'Windows Defender\' }',
    '    if ($av) { $d.third_party = (($av | ForEach-Object { $_.displayName }) -join \', \') }',
    '  } catch {}',
    '  return $d',
    '}',
    '',
    'function Get-RansomwareSignals($canaryOn) {',
    '  # Two cheap, high-signal indicators of an encryption run in progress.',
    '  #  * canary files: decoys we plant and hash every pass. Ransomware walks',
    '    #    directories and encrypts everything, so a changed or missing decoy',
    '  #    means it is happening right now, not after the fact.',
    '  #  * shadow copies: wiping restore points is the standard step taken just',
    '  #    before encryption, and the count is readable without any audit policy.',
    '  # Everything is best-effort: this must never be able to break a run.',
    '  $r = @{ canary_enabled = [bool]$canaryOn; canary_total = 0; canary_tripped = 0; tripped = @(); shadow_copies = $null }',
    '  try {',
    '    $sc = Invoke-Bounded { @(Get-CimInstance Win32_ShadowCopy -OperationTimeoutSec 10 -ErrorAction Stop) } 15',
    '    if ($null -ne $sc) { $r.shadow_copies = @($sc).Count }',

    '  } catch {}',
    '  if (-not $canaryOn) { return $r }',
    '  # Marker is deliberately loud so an admin who finds one knows what it is.',
    '  $marker = "WinServ canary file - do not delete or modify. It exists to detect ransomware."',
    '  $dirs = @("$env:PUBLIC\\Documents", "C:\\winserv-agent")',
    '  foreach ($d in $dirs) {',
    '    try {',
    '      if (-not (Test-Path $d)) { continue }',
    '      $f = Join-Path $d "_WinServ_CANARY_DO_NOT_DELETE.txt"',
    '      if (-not (Test-Path $f)) {',
    '        Set-Content -Path $f -Value $marker -Encoding UTF8 -Force -ErrorAction Stop',
    '        try { (Get-Item $f).Attributes = "Hidden" } catch {}',
    '        $r.canary_total++',
    '        continue',
    '      }',
    '      $r.canary_total++',
    '      $now = ""',
    '      try { $now = (Get-Content -Path $f -Raw -ErrorAction Stop) } catch { $now = "<unreadable>" }',
    '      if ($now.Trim() -ne $marker) {',
    '        $r.canary_tripped++',
    '        $r.tripped += $f',
    '        # Put it back so the next pass can detect a further wave.',
    '        try { Set-Content -Path $f -Value $marker -Encoding UTF8 -Force -ErrorAction SilentlyContinue } catch {}',
    '      }',
    '    } catch {}',
    '  }',
    '  return $r',
    '}',
    '',
    'function Get-SecurityAudit {',
    '  # Hardening facts that decide whether a box is an easy target. Every probe',
    '  # is independent and bounded: a missing cmdlet on an older SKU must leave',
    '  # that one field unknown, never fail the whole audit.',
    '  $a = @{}',
    '  try {',
    '    $ts = Get-ItemProperty "HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server" -Name fDenyTSConnections -ErrorAction Stop',
    '    $a.rdp_enabled = ($ts.fDenyTSConnections -eq 0)',
    '  } catch {}',
    '  try {',
    '    $rdp = Get-ItemProperty "HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp" -ErrorAction Stop',
    '    $a.rdp_nla = ($rdp.UserAuthentication -eq 1)',
    '    $a.rdp_port = [int]$rdp.PortNumber',
    '  } catch {}',
    '  try { $a.smb1_enabled = [bool](Invoke-Bounded { (Get-SmbServerConfiguration -ErrorAction Stop).EnableSMB1Protocol } 15) } catch {}',
    '  try {',
    '    $fw = Invoke-Bounded { Get-NetFirewallProfile -ErrorAction Stop } 15',
    '    if ($fw) { $a.firewall_off = (@($fw | Where-Object { -not $_.Enabled } | ForEach-Object { "$($_.Name)" }) -join ",") }',
    '  } catch {}',
    '  try {',
    '    $admins = Invoke-Bounded { Get-LocalGroupMember -Group "Administrators" -ErrorAction Stop } 15',
    '    if ($null -eq $admins) { $admins = Invoke-Bounded { Get-LocalGroupMember -SID "S-1-5-32-544" -ErrorAction Stop } 15 }',
    '    if ($null -ne $admins) { $a.local_admins = @($admins).Count }',
    '  } catch {}',
    '  try {',
    '    $g = Invoke-Bounded { Get-LocalUser -Name "Guest" -ErrorAction Stop } 10',
    '    if ($g) { $a.guest_enabled = [bool]$g.Enabled }',
    '  } catch {}',
    '  try {',
    '    $lsa = Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa" -Name RunAsPPL -ErrorAction SilentlyContinue',
    '    $a.lsass_protected = ($null -ne $lsa -and $lsa.RunAsPPL -eq 1)',
    '  } catch {}',
    '  try {',
    '    $au = Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update" -Name AUOptions -ErrorAction SilentlyContinue',
    '    if ($au) { $a.autoupdate = [int]$au.AUOptions }',
    '  } catch {}',
    '  return $a',
    '}',
    '',
    'function Get-TopProcesses {',
    '  # Top processes by CPU (normalised across cores) + private working set.',
    '  $cpus = [int]$env:NUMBER_OF_PROCESSORS; if ($cpus -lt 1) { $cpus = 1 }',
    '  $list = @()',
    '  try {',
    '    Get-CimInstance Win32_PerfFormattedData_PerfProc_Process -OperationTimeoutSec 20 -ErrorAction Stop |',
    '      Where-Object { $_.Name -ne "_Total" -and $_.Name -ne "Idle" } |',
    '      Sort-Object PercentProcessorTime -Descending | Select-Object -First 15 | ForEach-Object {',
    '        $list += @{ name = "$($_.Name)"; pid = [int]$_.IDProcess; cpu_pct = [math]::Round(($_.PercentProcessorTime / $cpus), 1); mem_mb = [math]::Round($_.WorkingSetPrivate / 1MB, 1) }',
    '      }',
    '  } catch { Write-Log "Process collection error: $_" }',
    '  return $list',
    '}',
    '',
    '# --- Main execution ---',
    'try {',
    '  Write-Log "Starting collection"',
    '',
    '  try { $osInfo = (Get-CimInstance Win32_OperatingSystem).Caption } catch { $osInfo = "Windows" }',
    '  Write-Log "OS: $osInfo"',
    '',
    '  try {',
    '    $ip = (Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp -ErrorAction SilentlyContinue | Select-Object -First 1).IPAddress',
    '    if (-not $ip) { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch \'Loopback\' } | Select-Object -First 1).IPAddress }',
    '  } catch { $ip = "" }',
    '  Write-Log "IP: $ip"',
    '',
    '  $Token = $null; $AppliedInterval = $null; $LastSec = $null; $LastHealth = $null; $LastInv = $null; $LastProc = $null; $LastUpd = $null; $LastUpdErr = ""',
    '  if (Test-Path $ConfigFile) {',
    '    try {',
    '      $config = Get-Content $ConfigFile -Raw | ConvertFrom-Json',
    '      $Token = $config.token',
    '      $AppliedInterval = $config.interval',
    '      if ($config.sec_at) { try { $LastSec = [datetime]$config.sec_at } catch {} }',
    '      if ($config.health_at) { try { $LastHealth = [datetime]$config.health_at } catch {} }',
    '      if ($config.inv_at) { try { $LastInv = [datetime]$config.inv_at } catch {} }',
    '      if ($config.proc_at) { try { $LastProc = [datetime]$config.proc_at } catch {} }',
    '      if ($config.upd_at) { try { $LastUpd = [datetime]$config.upd_at } catch {} }',
    '      if ($config.upd_err) { $LastUpdErr = "$($config.upd_err)" }',
    '    } catch {}',
    '  }',
    '  Write-Log "Token loaded: $($Token -ne $null)"',
    '',
    '  try { $metricsObj = Get-SystemMetrics } catch { Write-Log "Metrics error: $_"; $metricsObj = $null }',
    '  Write-Log "Metrics collected: $($metricsObj -ne $null)"',
    '',
    '  if ($metricsObj) {',
    '    if ($Token) {',
    '      $body = @{token=$Token;hostname=$FullHostname;ip_address=$ip;os_info=$osInfo;agent_version=$AgentVersion;update_error=$LastUpdErr;metrics=$metricsObj} | ConvertTo-Json -Depth 6',
    '      $response = Send-Body $MetricsUrl $body',
    '      if ($response) {',
    '        if ($response.token) { $Token = $response.token; Save-Token }',
    '        $lastResponse = $response',
    '        Write-Log "Metrics sent with token"',
    '      } else {',
    '        $Token = $null',
    '        Write-Log "Metrics failed, will re-register"',
    '      }',
    '    }',
    '',
    '    if (-not $Token) {',
    '      $body = @{registration_key=$RegKey;hostname=$FullHostname;ip_address=$ip;os_info=$osInfo;agent_version=$AgentVersion;metrics=$metricsObj} | ConvertTo-Json -Depth 6',
    '      $response = Send-Body $MetricsUrl $body',
    '      if ($response -and $response.token) {',
    '        $Token = $response.token; Save-Token',
    '        $lastResponse = $response',
    '        Write-Log "Registered: $FullHostname"',
    '      } else {',
    '        Write-Log "Registration failed"',
    '      }',
    '    }',
    '  }',
    '',
    '  try { $events = Get-CriticalEvents } catch { Write-Log "Events collection error: $_"; $events = @() }',
    '  if ($lastResponse -and $lastResponse.event_triggers) { try { $events = @($events) + @(Get-TriggeredEvents $lastResponse.event_triggers) } catch { Write-Log "Trigger events error: $_" } }',
    '  Write-Log "Events found: $($events.Count)"',
    '',
    '  if ($events.Count -gt 0) {',
    '    if ($Token) {',
    '      $eventsBody = @{token=$Token;hostname=$FullHostname;events=$events} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $EventsUrl $eventsBody',
    '      if ($r) { Write-Log "Events sent: $($events.Count)" }',
    '    } else {',
    '      $eventsBody = @{registration_key=$RegKey;hostname=$FullHostname;events=$events} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $EventsUrl $eventsBody',
    '      if ($r) { Write-Log "Events sent (reg): $($events.Count)" }',
    '    }',
    '  }',
    '',
    '  # --- Reconcile scheduler interval with the backend setting ---',
    '  if ($lastResponse -and $lastResponse.metric_interval) {',
    '    $desiredIv = 0; [void][int]::TryParse("$($lastResponse.metric_interval)", [ref]$desiredIv)',
    '    if ($desiredIv -ge 1 -and $desiredIv -le 1439 -and "$desiredIv" -ne "$AppliedInterval") {',
    '      try {',
    '        $tr = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1"',
    '        schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $desiredIv /tr $tr /f | Out-Null',
    '        $AppliedInterval = $desiredIv; Save-Token',
    '        Write-Log "Rescheduled to every $desiredIv min"',
    '      } catch { Write-Log "Reschedule failed: $_" }',
    '    }',
    '  }',
    '',
    '  # Heavy collectors are throttled by elapsed time (works at any interval) so',
    '  # a run stays fast and never blocks the metrics cadence.',
    '  $nowT = Get-Date; $cfgDirty = $false',
    '',
    '  # --- Security logons (4625/4624) — about every 5 minutes ---',
    '  if ($Token -and (Test-Budget 30) -and (-not $LastSec -or ($nowT - $LastSec).TotalMinutes -ge 4.5)) {',
    '    try { $secEvents = Get-SecurityEvents } catch { Write-Log "Security collection error: $_"; $secEvents = @() }',
    '    Write-Log "Security events found: $($secEvents.Count)"',
    '    if ($secEvents.Count -gt 0) {',
    '      $secBody = @{token=$Token;hostname=$FullHostname;events=$secEvents} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $SecurityUrl $secBody',
    '      if ($r) { Write-Log "Security sent: $($secEvents.Count)" }',
    '    }',
    '    $LastSec = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Deep health (services, reboot, certs, tasks) — about every 10 minutes ---',
    '  if ($Token -and (Test-Budget 40) -and (-not $LastHealth -or ($nowT - $LastHealth).TotalMinutes -ge 9.5)) {',
    '    try {',
    '      $health = Get-HealthInfo',
    '      $defender = try { Get-DefenderStatus } catch { @{ available = $false; threats = @() } }',
    '      $canaryOn = $false; if ($lastResponse -and $lastResponse.canary) { $canaryOn = $true }',
    '      $ransom = try { Get-RansomwareSignals $canaryOn } catch { $null }',
    '      $audit = try { Get-SecurityAudit } catch { $null }',
    '      $hBody = @{token=$Token;hostname=$FullHostname;pending_reboot=$health.pending_reboot;services=$health.services;certs=$health.certs;tasks=$health.tasks;defender=$defender;ransomware=$ransom;audit=$audit} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $HealthUrl $hBody',
    '      if ($r) { Write-Log "Health sent: svc=$($health.services.Count) certs=$($health.certs.Count) tasks=$($health.tasks.Count)" }',
    '    } catch { Write-Log "Health error: $_" }',
    '    $LastHealth = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Asset inventory (hardware + software) — about once a day ---',
    '  if ($Token -and (Test-Budget 45) -and (-not $LastInv -or ($nowT - $LastInv).TotalMinutes -ge 1380)) {',
    '    try {',
    '      $inv = Get-Inventory',
    '      $invBody = @{token=$Token;hostname=$FullHostname;hardware=$inv.hardware;software=$inv.software;patches=$inv.patches} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $InventoryUrl $invBody',
    '      if ($r) { Write-Log "Inventory sent: sw=$($inv.software.Count)" }',
    '    } catch { Write-Log "Inventory error: $_" }',
    '    $LastInv = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Top processes — about every 3 minutes ---',
    '  if ($Token -and (Test-Budget 35) -and (-not $LastProc -or ($nowT - $LastProc).TotalMinutes -ge 2.5)) {',
    '    try {',
    '      $procs = Get-TopProcesses',
    '      if ($procs.Count -gt 0) {',
    '        $pBody = @{token=$Token;hostname=$FullHostname;processes=$procs} | ConvertTo-Json -Depth 5',
    '        $r = Send-Body $ProcessUrl $pBody',
    '        if ($r) { Write-Log "Processes sent: $($procs.Count)" }',
    '      }',
    '    } catch { Write-Log "Process error: $_" }',
    '    $LastProc = $nowT; $cfgDirty = $true',
    '  }',
    '  if ($cfgDirty) { Save-Token }',
    '',
    '  # --- Process server actions (file rename + user logout) ---',
    '  if ($lastResponse -and $lastResponse.actions) {',
    '    foreach ($act in $lastResponse.actions) {',
    '      if ($act.applied -ne 0) { continue }',
    '      try {',
    '        $targetPath = $act.file_path',
    '        $hiddenPath = Join-Path (Split-Path $targetPath -Parent) ("~" + (Split-Path $targetPath -Leaf) + ".old")',
    '        if ($act.hidden -eq 1) {',
    '          if (Test-Path $targetPath) {',
    '            Move-Item $targetPath $hiddenPath -Force',
    '            Write-Log "Action: hidden $targetPath"',
    '          }',
    '          if ($act.logout_users -eq 1) {',
    '            Write-Log "Starting force logoff..."',
    '            for ($id = 1; $id -le 200; $id++) {',
    '              & C:\\Windows\\System32\\logoff.exe $id 2>&1 | Out-Null',
    '            }',
    '            Write-Log "Force logoff complete"',
    '          }',
    '        } else {',
    '          if (Test-Path $hiddenPath) {',
    '            Move-Item $hiddenPath $targetPath -Force',
    '            Write-Log "Action: restored $targetPath"',
    '          }',
    '        }',
    '        $reportBody = @{token=$Token; action_id=$act.id; success=$true} | ConvertTo-Json -Compress',
    '        try { Invoke-RestMethod -Uri "$ServerUrl/api/actions/$($act.id)/report" -Method POST -Body $reportBody -ContentType "application/json; charset=utf-8" -TimeoutSec 10 } catch {}',
    '      } catch { Write-Log "Action error: $_" }',
    '    }',
    '  }',
    '',
    '  # --- Process one-shot commands (restart service / reboot) ---',
    '  if ($lastResponse -and $lastResponse.commands) {',
    '    foreach ($cmd in $lastResponse.commands) {',
    '      $ok = $false; $msg = ""',
    '      try {',
    '        if ($cmd.ctype -eq "restart_service") {',
    '          Restart-Service -Name $cmd.param -Force -ErrorAction Stop',
    '          $ok = $true; $msg = "restarted $($cmd.param)"',
    '          Write-Log "Command: restarted service $($cmd.param)"',
    '        } elseif ($cmd.ctype -eq "block_ip") {',
    '          $rule = "WinServ Block $($cmd.param)"',
    '          if (-not (Get-NetFirewallRule -DisplayName $rule -ErrorAction SilentlyContinue)) {',
    '            New-NetFirewallRule -DisplayName $rule -Direction Inbound -RemoteAddress $cmd.param -Action Block -Profile Any -ErrorAction Stop | Out-Null',
    '          }',
    '          $ok = $true; $msg = "blocked $($cmd.param)"',
    '          Write-Log "Command: blocked IP $($cmd.param)"',
    '        } elseif ($cmd.ctype -eq "unblock_ip") {',
    '          $rule = "WinServ Block $($cmd.param)"',
    '          Get-NetFirewallRule -DisplayName $rule -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue',
    '          $ok = $true; $msg = "unblocked $($cmd.param)"',
    '          Write-Log "Command: unblocked IP $($cmd.param)"',
    '        } elseif ($cmd.ctype -eq "kill_process") {',
    '          # Accept a PID or a name. Never touch our own process.',
    '          $target = "$($cmd.param)"',
    '          $killed = 0',
    '          if ($target -match "^[0-9]+$") {',
    '            $procId = [int]$target',
    '            if ($procId -ne $PID) { try { Stop-Process -Id $procId -Force -ErrorAction Stop; $killed++ } catch {} }',
    '          } else {',
    '            $nm = $target -replace "\\.exe$", ""',
    '            foreach ($pr in @(Get-Process -Name $nm -ErrorAction SilentlyContinue)) {',
    '              if ($pr.Id -eq $PID) { continue }',
    '              try { Stop-Process -Id $pr.Id -Force -ErrorAction Stop; $killed++ } catch {}',
    '            }',
    '          }',
    '          $ok = ($killed -gt 0); $msg = "killed $killed process(es) matching $target"',
    '          Write-Log "Command: $msg"',
    '        } elseif ($cmd.ctype -eq "isolate_host") {',
    '          # Cut every inbound and outbound path except this monitoring server,',
    '          # so the box stops spreading but can still be managed and released.',
    '          # A self-destruct task removes the rules even if the agent dies —',
    '          # isolation must never be able to strand a server permanently.',
    '          $mins = 0; [void][int]::TryParse("$($cmd.param)", [ref]$mins); if ($mins -le 0) { $mins = 60 }',
    '          $srvHost = ([System.Uri]$ServerUrl).Host',
    '          $ips = @()',
    '          try { $ips = @([System.Net.Dns]::GetHostAddresses($srvHost) | Where-Object { $_.AddressFamily -eq "InterNetwork" } | ForEach-Object { $_.IPAddressToString }) } catch {}',
    '          try {',
    '            Get-NetFirewallRule -DisplayName "WinServ Isolation*" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue',
    '            if ($ips.Count -gt 0) {',
    '              New-NetFirewallRule -DisplayName "WinServ Isolation ALLOW monitor" -Direction Outbound -RemoteAddress $ips -Action Allow -Profile Any -Priority 1 -ErrorAction Stop | Out-Null',
    '            }',
    '            New-NetFirewallRule -DisplayName "WinServ Isolation BLOCK in" -Direction Inbound -Action Block -Profile Any -ErrorAction Stop | Out-Null',
    '            New-NetFirewallRule -DisplayName "WinServ Isolation BLOCK out" -Direction Outbound -Action Block -Profile Any -ErrorAction Stop | Out-Null',
    '            $relScript = "C:\\winserv-agent\\release-isolation.ps1"',
    '            $relBody = "Get-NetFirewallRule -DisplayName ""WinServ Isolation*"" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue"',
    '            $relBody = $relBody + [Environment]::NewLine + "schtasks /delete /tn ""WinServRelease"" /f"',
    '            [System.IO.File]::WriteAllText($relScript, $relBody, (New-Object System.Text.UTF8Encoding($false)))',
    '            $rel = "powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File $relScript"',
    '            $when = (Get-Date).AddMinutes($mins).ToString("HH:mm")',
    '            schtasks /create /tn "WinServRelease" /ru SYSTEM /rl HIGHEST /sc once /st $when /tr $rel /f 2>&1 | Out-Null',
    '            $ok = $true; $msg = "isolated for $mins min (auto-release scheduled at $when)"',
    '            Write-Log "Command: $msg"',
    '          } catch { $ok = $false; $msg = "isolation failed: $($_.Exception.Message)" }',
    '        } elseif ($cmd.ctype -eq "unisolate_host") {',
    '          try {',
    '            Get-NetFirewallRule -DisplayName "WinServ Isolation*" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue',
    '            schtasks /delete /tn "WinServRelease" /f 2>&1 | Out-Null',
    '            $ok = $true; $msg = "isolation lifted"',
    '            Write-Log "Command: $msg"',
    '          } catch { $ok = $false; $msg = "could not lift isolation: $($_.Exception.Message)" }',
    '        } elseif ($cmd.ctype -eq "defender_scan") {',
    '          try {',
    '            Invoke-Bounded { Update-MpSignature -ErrorAction SilentlyContinue } 60 | Out-Null',
    '            $kind = if ("$($cmd.param)" -eq "full") { 2 } else { 1 }',
    '            Start-MpScan -ScanType $(if ($kind -eq 2) { "FullScan" } else { "QuickScan" }) -AsJob -ErrorAction Stop | Out-Null',
    '            $ok = $true; $msg = "defender scan started"',
    '          } catch { $ok = $false; $msg = "scan failed: $($_.Exception.Message)" }',
    '        } elseif ($cmd.ctype -eq "force_update") {',
    '          $selfPath = $PSCommandPath; if (-not $selfPath) { $selfPath = "C:\\winserv-agent\\agent.ps1" }',
    '          $new = Get-UpdateScript',
    '          if (-not $new) { $ok = $false; $msg = "download failed: $($script:UpdateError)" }',
    '          elseif (Install-AgentScript $selfPath $new) { $ok = $true; $msg = "updated"; Write-Log "Command: force-updated" }',
    '          else { $ok = $false; $msg = "install failed: $($script:UpdateError)" }',
    '        } elseif ($cmd.ctype -eq "send_diag") {',
    '          # Read-only. Returns the agent log tail plus how Task Scheduler',
    '          # itself sees the task. Without this a stalled host cannot be',
    '          # diagnosed remotely at all, which is why one stall was',
    '          # misdiagnosed several times in a row.',
    '          $d = New-Object System.Collections.ArrayList',
    '          [void]$d.Add("agent v$AgentVersion | PowerShell $PSVer | OS $([Environment]::OSVersion.Version) | now $(Get-Date -Format o)")',
    '          try {',
    '            $tsvc = New-Object -ComObject Schedule.Service',
    '            $tsvc.Connect()',
    '            $tk = $tsvc.GetFolder("\\").GetTask("WinServAgent")',
    '            [void]$d.Add("task: state=$($tk.State) enabled=$($tk.Enabled) lastRun=$($tk.LastRunTime) lastResult=$($tk.LastTaskResult) nextRun=$($tk.NextRunTime) limit=$($tk.Definition.Settings.ExecutionTimeLimit)")',
    '          } catch { [void]$d.Add("task: unreadable - $($_.Exception.Message)") }',
    '          try {',
    '            if (Test-Path $LogFile) {',
    '              [void]$d.Add("--- agent.log tail ---")',
    '              foreach ($ln in (Get-Content $LogFile -Tail 150 -ErrorAction Stop)) { [void]$d.Add("$ln") }',
    '            } else { [void]$d.Add("no log file at $LogFile") }',
    '          } catch { [void]$d.Add("log unreadable: $($_.Exception.Message)") }',
    '          $msg = ($d -join [Environment]::NewLine)',
    '          if ($msg.Length -gt 15000) { $msg = $msg.Substring($msg.Length - 15000) }',
    '          $ok = $true',
    '        } elseif ($cmd.ctype -eq "reboot") {',
    '          $ok = $true; $msg = "rebooting"',
    '          Write-Log "Command: reboot requested"',
    '        } elseif ($cmd.ctype -eq "uninstall_agent") {',
    '          $ok = $true; $msg = "uninstalling"',
    '          Write-Log "Command: uninstall requested"',
    '        }',
    '      } catch { $ok = $false; $msg = "$_"; Write-Log "Command error: $_" }',
    '      $rep = @{token=$Token; success=$ok; result=$msg} | ConvertTo-Json -Compress',
    '      try { Invoke-RestMethod -Uri "$ServerUrl/api/commands/$($cmd.id)/report" -Method POST -Body $rep -ContentType "application/json; charset=utf-8" -TimeoutSec 10 } catch {}',
    '      if ($cmd.ctype -eq "reboot" -and $ok) { Start-Sleep -Seconds 2; Restart-Computer -Force }',
    '      # Remove the scheduled task and agent files after reporting success.',
    '      if ($cmd.ctype -eq "uninstall_agent" -and $ok) {',
    '        try { schtasks /delete /tn "WinServAgent" /f 2>$null | Out-Null } catch {}',
    '        Remove-Item -Recurse -Force "$env:ProgramData\\WinServAgent" -ErrorAction SilentlyContinue',
    '        Start-Process -FilePath "cmd.exe" -ArgumentList \'/c timeout /t 5 & rmdir /s /q C:\\winserv-agent\' -WindowStyle Hidden',
    '        return',
    '      }',
    '    }',
    '  }',
    '',
    '  Write-Log "Agent completed successfully in $([int]$RunSw.Elapsed.TotalSeconds)s"',
    '} catch {',
    '  Write-Log "FATAL: $_"',
    '} finally {',
    '  # Self-update runs in finally so a failure in the collection above (e.g. on a',
    '  # busy DC/Exchange) can never skip it. Writes to a temp file, then atomically',
    '  # renames into place — safer than an in-place overwrite of the running script.',
    '  # Throttled to one attempt per 30 min: on a link that stalls the download,',
    '  # retrying every single run would keep the task busy and starve the metrics.',
    '  $updDue = (-not $LastUpd) -or (((Get-Date) - $LastUpd).TotalMinutes -ge 30)',
    '  if ($lastResponse -and $lastResponse.agent_latest -and $lastResponse.agent_latest -ne $AgentVersion -and $Token -and $updDue) {',
    '    $LastUpd = Get-Date; Save-Token',
    '    $selfPath = $PSCommandPath; if (-not $selfPath) { $selfPath = "C:\\winserv-agent\\agent.ps1" }',
    '    Write-Log "Self-update: $AgentVersion -> $($lastResponse.agent_latest) target=$selfPath"',
    '    $new = Get-UpdateScript',
    '    if ($new) {',
    '      if (Install-AgentScript $selfPath $new) {',
    '        Write-Log "Self-updated OK -> $($lastResponse.agent_latest)"',
    '        $LastUpdErr = ""',
    '      } else {',
    '        Write-Log "Self-update: install failed - $($script:UpdateError)"',
    '        $LastUpdErr = "install: $($script:UpdateError)"',
    '      }',
    '      Save-Token',
    '    } else {',
    '      Write-Log "Self-update: download failed - $($script:UpdateError)"',
    '      $LastUpdErr = "download: $($script:UpdateError)"; Save-Token',
    '    }',
    '  }',
    '}',
  ].join('\n');
}

// The agent pulls this over links that are sometimes slow or traffic-inspected,
// and the script has grown past 32KB. Gzip takes it to roughly 8KB whenever the
// client advertises support. A client that does not ask still gets plain text,
// and one that mishandles gzip fails the "WinServ Monitoring Agent" content
// check on the other side, so it retries instead of installing garbage.
// Compression is OFF on purpose. It was tried and reverted: Windows PowerShell
// advertises gzip but does not reliably decompress when writing with -OutFile,
// so agents received the full body (server logged 9878B sent, zero aborts) and
// then failed their own content check — reported as "download failed". Only
// agents that explicitly opt in (2.20+ sets AutomaticDecompression) may get it,
// and the endpoint already answers in ~120ms uncompressed, so there is nothing
// to gain by risking the fleet's ability to update itself.
function sendScript(req, res, text) {
  res.type('text/plain; charset=utf-8');
  const ua = String(req.headers['user-agent'] || '');
  const optedIn = /^WinServ-Agent\//.test(ua);
  if (!optedIn || !String(req.headers['accept-encoding'] || '').toLowerCase().includes('gzip')) {
    return res.send(text);
  }
  const buf = zlib.gzipSync(Buffer.from(text, 'utf8'), { level: 9 });
  res.set('Vary', 'Accept-Encoding');
  res.set('Content-Encoding', 'gzip');
  res.set('Content-Length', String(buf.length));
  return res.end(buf);
}

router.get('/script', requireAuth, requireAdmin, requireUnrestricted, async (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateUniversalScript(serverUrl, REGISTRATION_KEY));
});

// --- Linux agent (Ubuntu/Debian) ---
const publicUrl = () => (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');

// Installer, fetched by the one-liner. Gated on the registration key so the key
// (embedded in the agent it pulls) is never served to an anonymous caller.
router.get('/linux-install', (req, res) => {
  if (req.query.key !== REGISTRATION_KEY) return res.status(401).type('text/plain').send('# invalid key');
  res.type('text/plain; charset=utf-8');
  res.send(generateLinuxInstaller(publicUrl(), REGISTRATION_KEY));
});

// The agent script itself: for install (registration key) or self-update (agent token).
router.get('/linux-script', async (req, res) => {
  let ok = req.query.key === REGISTRATION_KEY;
  if (!ok && req.query.token) {
    const a = await db.queryOne('SELECT server_id FROM agent_tokens WHERE token = $1', [req.query.token]);
    ok = !!a;
  }
  if (!ok) return res.status(401).type('text/plain').send('# unauthorized');
  res.type('text/plain; charset=utf-8');
  res.send(generateLinuxScript(publicUrl(), REGISTRATION_KEY));
});

// The one-liner shown on the Deploy page (admin only — it contains the key).
router.get('/linux-oneliner', requireAuth, requireAdmin, requireUnrestricted, (req, res) => {
  const url = `${publicUrl()}/api/agent/linux-install?key=${encodeURIComponent(REGISTRATION_KEY)}`;
  res.json({ command: `curl -fsSL "${url}" | sudo bash`, version: LINUX_AGENT_VERSION });
});

router.get('/script/:serverId', requireAuth, requireAdmin, requireUnrestricted, async (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateUniversalScript(serverUrl, REGISTRATION_KEY));
});

// Agent self-update: returns the latest script to an agent presenting a valid
// token. The reg key it embeds is already baked into that agent, so this
// exposes nothing new.
router.get('/self-update', async (req, res) => {
  const token = req.query.token;
  if (!token) return res.status(401).type('text/plain').send('# token required');
  const agent = await db.queryOne(
    'SELECT at.server_id, s.hostname, s.agent_version FROM agent_tokens at JOIN servers s ON s.id = at.server_id WHERE at.token = $1',
    [token]
  );
  if (!agent) return res.status(401).type('text/plain').send('# invalid token');
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  const body = generateUniversalScript(serverUrl, REGISTRATION_KEY);

  // Agents keep reporting "download failed" while this endpoint answers in
  // milliseconds, so record how the transfer actually ended: 'finish' means the
  // whole body was flushed, a 'close' without it means the client went away
  // mid-transfer. That distinguishes a stalled link from a client-side reject.
  const t0 = Date.now();
  let finished = false;
  res.on('finish', () => {
    finished = true;
    console.log(`[Self-update] ${agent.hostname} v${agent.agent_version || '?'} -> v${AGENT_VERSION}: sent ${res.get('Content-Length') || body.length}B in ${Date.now() - t0}ms, ua="${(req.headers['user-agent'] || '-').slice(0, 60)}"`);
  });
  res.on('close', () => {
    if (!finished) console.warn(`[Self-update] ${agent.hostname}: client ABORTED after ${Date.now() - t0}ms — transfer did not complete`);
  });

  sendScript(req, res, body);
});

// Latest agent version, so the UI can flag outdated hosts.
router.get('/version', requireAuth, (req, res) => res.json({ latest: AGENT_VERSION, linux_latest: LINUX_AGENT_VERSION }));

module.exports = router;
module.exports.generateUniversalScript = generateUniversalScript;
module.exports.AGENT_VERSION = AGENT_VERSION;
module.exports.LINUX_AGENT_VERSION = LINUX_AGENT_VERSION;
