const express = require('express');
const { requireAuth, requireAdmin } = require('../middleware/authMiddleware');

const router = express.Router();
const REGISTRATION_KEY = process.env.REGISTRATION_KEY || 'winserv-reg-key-change-me';
const AGENT_VERSION = '2.12';

function generateUniversalScript(serverUrl, regKey) {
  return [
    '# WinServ Monitoring Agent v' + AGENT_VERSION,
    '# ====================================================================',
    '# Auto-registers on first run. One script for all servers.',
    '# Save to C:\\winserv-agent\\agent.ps1 and schedule:',
    '#   schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo 1 /tr "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1" /f',
    '# ====================================================================',
    'try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}',
    '[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 -bor [System.Net.SecurityProtocolType]::Tls13',
    '',
    '$ErrorActionPreference = "Continue"',
    '$AgentVersion = "' + AGENT_VERSION + '"',
    '$ServerUrl = "' + serverUrl + '"',
    '$MetricsUrl = "$ServerUrl/api/metrics"',
    '$EventsUrl = "$ServerUrl/api/events"',
    '$SecurityUrl = "$ServerUrl/api/security"',
    '$HealthUrl = "$ServerUrl/api/health-report"',
    '$InventoryUrl = "$ServerUrl/api/inventory-report"',
    '$ProcessUrl = "$ServerUrl/api/process-report"',
    '$RegKey = "' + regKey + '"',
    '$ConfigFile = "$env:ProgramData\\WinServAgent\\config.json"',
    '$LogFile = "$env:ProgramData\\WinServAgent\\agent.log"',
    '',
    '# Heartbeat: write timestamp to prove script started',
    'try { Get-Date -Format \'yyyy-MM-dd HH:mm:ss\' | Out-File "C:\\winserv-agent\\heartbeat.txt" -Encoding UTF8 } catch {}',
    '',
    'function Write-Log($msg) {',
    '  $dir = Split-Path $LogFile -Parent',
    '  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }',
    '  $ts = Get-Date -Format \'yyyy-MM-dd HH:mm:ss\'',
    '  "$ts $msg" | Out-File $LogFile -Append -Encoding UTF8',
    '}',
    '',
    'Write-Log "Agent started"',
    '',
    '$FullHostname = try { [System.Net.Dns]::GetHostEntry(\'\').HostName } catch { "$env:COMPUTERNAME.$env:USERDNSDOMAIN" }',
    'if (-not $FullHostname -or $FullHostname -notmatch \'\\.\') { $FullHostname = "$env:COMPUTERNAME.$env:USERDNSDOMAIN" }',
    '',
    'function Get-SystemMetrics {',
    '  $cpu = (Get-CimInstance Win32_Processor | Measure-Object -Property LoadPercentage -Average).Average',
    '  $os = Get-CimInstance Win32_OperatingSystem',
    '  $memTotalMB = [math]::Round($os.TotalVisibleMemorySize / 1024, 0)',
    '  $memFreeMB = [math]::Round($os.FreePhysicalMemory / 1024, 0)',
    '  $memUsedMB = $memTotalMB - $memFreeMB',
    '  $disks = Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3" -ErrorAction SilentlyContinue',
    '  $diskPerf = @{}',
    '  try {',
    '    Get-CimInstance Win32_PerfFormattedData_PerfDisk_LogicalDisk -ErrorAction Stop | Where-Object { $_.Name -match \'^[A-Z]:$\' } | ForEach-Object {',
    '      $diskPerf[$_.Name] = @{',
    '        read_bytes_sec = [math]::Round($_.DiskReadBytesPerSec, 0)',
    '        write_bytes_sec = [math]::Round($_.DiskWriteBytesPerSec, 0)',
    '        disk_time_pct = [math]::Round($_.PercentDiskTime, 1)',
    '        queue_length = [math]::Round($_.CurrentDiskQueueLength, 1)',
    '      }',
    '    }',
    '  } catch {}',
    '  $diskArray = @()',
    '  $diskTotalGB = 0; $diskUsedGB = 0; $diskFreeGB = 0',
    '  foreach ($d in $disks) {',
    '    $sizeGB = [math]::Round($d.Size / 1GB, 1)',
    '    $freeGB = [math]::Round($d.FreeSpace / 1GB, 1)',
    '    $usedGB = [math]::Round(($d.Size - $d.FreeSpace) / 1GB, 1)',
    '    $diskTotalGB += $sizeGB',
    '    $diskFreeGB += $freeGB',
    '    $diskUsedGB += $usedGB',
    '    $perf = $diskPerf[$d.DeviceID]',
    '    $diskEntry = @{ drive = $d.DeviceID; total_gb = $sizeGB; used_gb = $usedGB; free_gb = $freeGB }',
    '    if ($perf) {',
    '      $diskEntry.read_bytes_sec = $perf.read_bytes_sec',
    '      $diskEntry.write_bytes_sec = $perf.write_bytes_sec',
    '      $diskEntry.disk_time_pct = $perf.disk_time_pct',
    '      $diskEntry.queue_length = $perf.queue_length',
    '    }',
    '    $diskArray += $diskEntry',
    '  }',
    '  $uptime = [math]::Round(((Get-Date) - $os.LastBootUpTime).TotalSeconds, 0)',
    '  return @{',
    '    cpu_usage = $cpu',
    '    memory_total_mb = $memTotalMB',
    '    memory_used_mb = $memUsedMB',
    '    disk_total_gb = $diskTotalGB',
    '    disk_used_gb = $diskUsedGB',
    '    disk_free_gb = $diskFreeGB',
    '    disks = $diskArray',
    '    uptime_seconds = $uptime',
    '  }',
    '}',
    '',
    'function Get-CriticalEvents {',
    '  $since = (Get-Date).AddMinutes(-30)',
    '  $events = $null',
    '  try {',
    '    $events = Get-WinEvent -FilterHashtable @{LogName=\'System\';Level=1,2,3;StartTime=$since} -MaxEvents 200 -ErrorAction Stop',
    '  } catch {',
    '    try {',
    '      $events = Get-EventLog -LogName System -EntryType Error,Warning -After $since -Newest 200 -ErrorAction Stop',
    '    } catch {',
    '      Write-Log "EventLog: cannot read System log"',
    '      return @()',
    '    }',
    '  }',
    '  if (-not $events) { return @() }',
    '  $result = @()',
    '  foreach ($e in $events) {',
    '    $source = if ($e.ProviderName) { $e.ProviderName } else { $e.Source }',
    '    $eid = if ($e.Id) { $e.Id } else { $e.EventID }',
    '    $lvlNum = if ($e.Level) { $e.Level } else { 2 }',
    '    if ($lvlNum -le 1) { $lvl = \'Critical\' }',
    '    elseif ($lvlNum -le 2) { $lvl = \'Error\' }',
    '    elseif ($lvlNum -le 3) { $lvl = \'Warning\' }',
    '    else { $lvl = \'Information\' }',
    '    try {',
    '      $msg = if ($e.Message) { if ($e.Message.Length -gt 2000) { $e.Message.Substring(0, 2000) } else { $e.Message } } else { \'\' }',
    '    } catch { $msg = \'\' }',
    '    $time = if ($e.TimeCreated) { $e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\') } else { $e.TimeGenerated.ToString(\'yyyy-MM-ddTHH:mm:ss\') }',
    '    $result += @{source=$source;event_id=$eid;level=$lvl;message=$msg;recorded_at=$time}',
    '  }',
    '  Write-Log "Events collected: $($result.Count)"',
    '  return $result',
    '}',
    '',
    'function Save-Token {',
    '  # Persists token + applied schedule interval + last heavy-collection times.',
    '  try {',
    '    $dir = Split-Path $ConfigFile -Parent',
    '    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }',
    '    $o = @{ token = $Token }',
    '    if ($AppliedInterval) { $o.interval = $AppliedInterval }',
    '    if ($LastSec) { $o.sec_at = $LastSec.ToString("o") }',
    '    if ($LastHealth) { $o.health_at = $LastHealth.ToString("o") }',
    '    if ($LastInv) { $o.inv_at = $LastInv.ToString("o") }',
    '    if ($LastProc) { $o.proc_at = $LastProc.ToString("o") }',
    '    $o | ConvertTo-Json | Set-Content $ConfigFile -Force',
    '  } catch { Write-Log "Save-Token error: $_" }',
    '}',
    '',
    'function Send-Body($url, $body) {',
    '  try {',
    '    return Invoke-RestMethod -Uri $url -Method POST -Body $body -ContentType "application/json; charset=utf-8" -TimeoutSec 15',
    '  } catch {',
    '    Write-Log "Send-Body $url : $_"',
    '    return $null',
    '  }',
    '}',
    '',
    'function Get-SecurityEvents {',
    '  # 4625 failed logons (brute-force signal) + 4624 RDP successes (type 10).',
    '  $since = (Get-Date).AddMinutes(-30)',
    '  try {',
    '    $events = Get-WinEvent -FilterHashtable @{LogName=\'Security\';Id=4624,4625;StartTime=$since} -MaxEvents 150 -ErrorAction Stop',
    '  } catch { return @() }',
    '  if (-not $events) { return @() }',
    '  $result = @()',
    '  foreach ($e in $events) {',
    '    try {',
    '      $x = [xml]$e.ToXml(); $d = @{}',
    '      foreach ($n in $x.Event.EventData.Data) { $d[$n.Name] = $n."#text" }',
    '      $lt = "$($d[\'LogonType\'])"',
    '      $ip = "$($d[\'IpAddress\'])"',
    '      $acct = "$($d[\'TargetUserName\'])"',
    '      if ($e.Id -eq 4625) {',
    '        if (-not $ip -or $ip -eq \'-\' -or $ip -eq \'::1\' -or $ip -eq \'127.0.0.1\') { continue }',
    '        $result += @{event=\'fail\';account=$acct;ip=$ip;logon_type=$lt;recorded_at=$e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\')}',
    '      } else {',
    '        if ($lt -ne \'10\') { continue }',
    '        $result += @{event=\'success\';account=$acct;ip=$ip;logon_type=$lt;recorded_at=$e.TimeCreated.ToString(\'yyyy-MM-ddTHH:mm:ss\')}',
    '      }',
    '    } catch {}',
    '  }',
    '  return $result',
    '}',
    '',
    'function Get-HealthInfo {',
    '  $h = @{ pending_reboot = $false; services = @(); certs = @(); tasks = @() }',
    '  try {',
    '    Get-CimInstance Win32_Service -Filter "StartMode=\'Auto\' AND State=\'Stopped\'" -ErrorAction Stop | ForEach-Object {',
    '      $h.services += @{ name = $_.Name; display = $_.DisplayName }',
    '    }',
    '  } catch {}',
    '  try {',
    '    if (Test-Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Component Based Servicing\\RebootPending") { $h.pending_reboot = $true }',
    '    if (Test-Path "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired") { $h.pending_reboot = $true }',
    '    $pfr = (Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue)',
    '    if ($pfr -and $pfr.PendingFileRenameOperations) { $h.pending_reboot = $true }',
    '  } catch {}',
    '  try {',
    '    $limit = (Get-Date).AddDays(30)',
    '    Get-ChildItem Cert:\\LocalMachine\\My -ErrorAction Stop | Where-Object { $_.NotAfter -lt $limit -and $_.NotAfter -gt (Get-Date).AddDays(-1) } | ForEach-Object {',
    '      $h.certs += @{ subject = $_.Subject; expires = $_.NotAfter.ToString(\'yyyy-MM-dd\') }',
    '    }',
    '  } catch {}',
    '  try {',
    '    Get-ScheduledTask -ErrorAction Stop | Where-Object { $_.State -ne "Disabled" } | ForEach-Object {',
    '      $info = $_ | Get-ScheduledTaskInfo -ErrorAction SilentlyContinue',
    '      if ($info -and $info.LastTaskResult -ne 0 -and $info.LastTaskResult -ne 267009 -and $info.LastTaskResult -ne 267011 -and $info.LastRunTime -gt (Get-Date).AddDays(-2)) {',
    '        $h.tasks += @{ name = $_.TaskName; result = $info.LastTaskResult }',
    '      }',
    '    }',
    '  } catch {}',
    '  return $h',
    '}',
    '',
    'function Get-Inventory {',
    '  # Hardware snapshot + installed software (from Uninstall registry keys).',
    '  $inv = @{ hardware = @{}; software = @() }',
    '  try {',
    '    $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue',
    '    $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue',
    '    $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '    $cpu = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1',
    '    $cores = (Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property NumberOfCores -Sum).Sum',
    '    $logical = (Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum',
    '    $ramGb = 0; if ($cs -and $cs.TotalPhysicalMemory) { $ramGb = [math]::Round($cs.TotalPhysicalMemory / 1GB, 1) }',
    '    $inv.hardware = @{',
    '      manufacturer = "$($cs.Manufacturer)"',
    '      model = "$($cs.Model)"',
    '      serial = "$($bios.SerialNumber)"',
    '      os_caption = "$($os.Caption)"',
    '      os_version = "$($os.Version)"',
    '      os_build = "$($os.BuildNumber)"',
    '      cpu = ("$($cpu.Name)").Trim()',
    '      cpu_cores = [int]$cores',
    '      cpu_logical = [int]$logical',
    '      ram_gb = $ramGb',
    '      disks = @()',
    '    }',
    '    Get-CimInstance Win32_DiskDrive -ErrorAction SilentlyContinue | ForEach-Object {',
    '      $szGb = 0; if ($_.Size) { $szGb = [math]::Round($_.Size / 1GB, 1) }',
    '      $inv.hardware.disks += @{ model = "$($_.Model)"; size_gb = $szGb; media = "$($_.MediaType)" }',
    '    }',
    '  } catch { Write-Log "Inventory hardware error: $_" }',
    '  try {',
    '    $paths = @("HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*", "HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*")',
    '    $seen = @{}',
    '    foreach ($p in $paths) {',
    '      Get-ItemProperty $p -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -and -not $_.SystemComponent -and -not $_.ReleaseType -and -not $_.ParentKeyName } | ForEach-Object {',
    '        $k = "$($_.DisplayName)|$($_.DisplayVersion)"',
    '        if (-not $seen.ContainsKey($k)) {',
    '          $seen[$k] = $true',
    '          $inv.software += @{ name = "$($_.DisplayName)"; version = "$($_.DisplayVersion)"; publisher = "$($_.Publisher)"; installed_on = "$($_.InstallDate)" }',
    '        }',
    '      }',
    '    }',
    '  } catch { Write-Log "Inventory software error: $_" }',
    '  return $inv',
    '}',
    '',
    'function Get-TopProcesses {',
    '  # Top processes by CPU (normalised across cores) + private working set.',
    '  $cpus = [int]$env:NUMBER_OF_PROCESSORS; if ($cpus -lt 1) { $cpus = 1 }',
    '  $list = @()',
    '  try {',
    '    Get-CimInstance Win32_PerfFormattedData_PerfProc_Process -ErrorAction Stop |',
    '      Where-Object { $_.Name -ne "_Total" -and $_.Name -ne "Idle" } |',
    '      Sort-Object PercentProcessorTime -Descending | Select-Object -First 15 | ForEach-Object {',
    '        $list += @{ name = "$($_.Name)"; pid = [int]$_.IDProcess; cpu_pct = [math]::Round(($_.PercentProcessorTime / $cpus), 1); mem_mb = [math]::Round($_.WorkingSetPrivate / 1MB, 1) }',
    '      }',
    '  } catch { Write-Log "Process collection error: $_" }',
    '  return $list',
    '}',
    '',
    '# --- Main execution ---',
    'try {',
    '  Write-Log "Starting collection"',
    '',
    '  try { $osInfo = (Get-CimInstance Win32_OperatingSystem).Caption } catch { $osInfo = "Windows" }',
    '  Write-Log "OS: $osInfo"',
    '',
    '  try {',
    '    $ip = (Get-NetIPAddress -AddressFamily IPv4 -PrefixOrigin Dhcp -ErrorAction SilentlyContinue | Select-Object -First 1).IPAddress',
    '    if (-not $ip) { $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch \'Loopback\' } | Select-Object -First 1).IPAddress }',
    '  } catch { $ip = "" }',
    '  Write-Log "IP: $ip"',
    '',
    '  $Token = $null; $AppliedInterval = $null; $LastSec = $null; $LastHealth = $null; $LastInv = $null; $LastProc = $null',
    '  if (Test-Path $ConfigFile) {',
    '    try {',
    '      $config = Get-Content $ConfigFile -Raw | ConvertFrom-Json',
    '      $Token = $config.token',
    '      $AppliedInterval = $config.interval',
    '      if ($config.sec_at) { try { $LastSec = [datetime]$config.sec_at } catch {} }',
    '      if ($config.health_at) { try { $LastHealth = [datetime]$config.health_at } catch {} }',
    '      if ($config.inv_at) { try { $LastInv = [datetime]$config.inv_at } catch {} }',
    '      if ($config.proc_at) { try { $LastProc = [datetime]$config.proc_at } catch {} }',
    '    } catch {}',
    '  }',
    '  Write-Log "Token loaded: $($Token -ne $null)"',
    '',
    '  try { $metricsObj = Get-SystemMetrics } catch { Write-Log "Metrics error: $_"; $metricsObj = $null }',
    '  Write-Log "Metrics collected: $($metricsObj -ne $null)"',
    '',
    '  if ($metricsObj) {',
    '    if ($Token) {',
    '      $body = @{token=$Token;hostname=$FullHostname;ip_address=$ip;os_info=$osInfo;agent_version=$AgentVersion;metrics=$metricsObj} | ConvertTo-Json -Depth 6',
    '      $response = Send-Body $MetricsUrl $body',
    '      if ($response) {',
    '        if ($response.token) { $Token = $response.token; Save-Token }',
    '        $lastResponse = $response',
    '        Write-Log "Metrics sent with token"',
    '      } else {',
    '        $Token = $null',
    '        Write-Log "Metrics failed, will re-register"',
    '      }',
    '    }',
    '',
    '    if (-not $Token) {',
    '      $body = @{registration_key=$RegKey;hostname=$FullHostname;ip_address=$ip;os_info=$osInfo;agent_version=$AgentVersion;metrics=$metricsObj} | ConvertTo-Json -Depth 6',
    '      $response = Send-Body $MetricsUrl $body',
    '      if ($response -and $response.token) {',
    '        $Token = $response.token; Save-Token',
    '        $lastResponse = $response',
    '        Write-Log "Registered: $FullHostname"',
    '      } else {',
    '        Write-Log "Registration failed"',
    '      }',
    '    }',
    '  }',
    '',
    '  try { $events = Get-CriticalEvents } catch { Write-Log "Events collection error: $_"; $events = @() }',
    '  Write-Log "Events found: $($events.Count)"',
    '',
    '  if ($events.Count -gt 0) {',
    '    if ($Token) {',
    '      $eventsBody = @{token=$Token;hostname=$FullHostname;events=$events} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $EventsUrl $eventsBody',
    '      if ($r) { Write-Log "Events sent: $($events.Count)" }',
    '    } else {',
    '      $eventsBody = @{registration_key=$RegKey;hostname=$FullHostname;events=$events} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $EventsUrl $eventsBody',
    '      if ($r) { Write-Log "Events sent (reg): $($events.Count)" }',
    '    }',
    '  }',
    '',
    '  # --- Reconcile scheduler interval with the backend setting ---',
    '  if ($lastResponse -and $lastResponse.metric_interval) {',
    '    $desiredIv = 0; [void][int]::TryParse("$($lastResponse.metric_interval)", [ref]$desiredIv)',
    '    if ($desiredIv -ge 1 -and $desiredIv -le 1439 -and "$desiredIv" -ne "$AppliedInterval") {',
    '      try {',
    '        $tr = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1"',
    '        schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $desiredIv /tr $tr /f | Out-Null',
    '        $AppliedInterval = $desiredIv; Save-Token',
    '        Write-Log "Rescheduled to every $desiredIv min"',
    '      } catch { Write-Log "Reschedule failed: $_" }',
    '    }',
    '  }',
    '',
    '  # Heavy collectors are throttled by elapsed time (works at any interval) so',
    '  # a run stays fast and never blocks the metrics cadence.',
    '  $nowT = Get-Date; $cfgDirty = $false',
    '',
    '  # --- Security logons (4625/4624) — about every 5 minutes ---',
    '  if ($Token -and (-not $LastSec -or ($nowT - $LastSec).TotalMinutes -ge 4.5)) {',
    '    try { $secEvents = Get-SecurityEvents } catch { Write-Log "Security collection error: $_"; $secEvents = @() }',
    '    Write-Log "Security events found: $($secEvents.Count)"',
    '    if ($secEvents.Count -gt 0) {',
    '      $secBody = @{token=$Token;hostname=$FullHostname;events=$secEvents} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $SecurityUrl $secBody',
    '      if ($r) { Write-Log "Security sent: $($secEvents.Count)" }',
    '    }',
    '    $LastSec = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Deep health (services, reboot, certs, tasks) — about every 10 minutes ---',
    '  if ($Token -and (-not $LastHealth -or ($nowT - $LastHealth).TotalMinutes -ge 9.5)) {',
    '    try {',
    '      $health = Get-HealthInfo',
    '      $hBody = @{token=$Token;hostname=$FullHostname;pending_reboot=$health.pending_reboot;services=$health.services;certs=$health.certs;tasks=$health.tasks} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $HealthUrl $hBody',
    '      if ($r) { Write-Log "Health sent: svc=$($health.services.Count) certs=$($health.certs.Count) tasks=$($health.tasks.Count)" }',
    '    } catch { Write-Log "Health error: $_" }',
    '    $LastHealth = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Asset inventory (hardware + software) — about once a day ---',
    '  if ($Token -and (-not $LastInv -or ($nowT - $LastInv).TotalMinutes -ge 1380)) {',
    '    try {',
    '      $inv = Get-Inventory',
    '      $invBody = @{token=$Token;hostname=$FullHostname;hardware=$inv.hardware;software=$inv.software} | ConvertTo-Json -Depth 6',
    '      $r = Send-Body $InventoryUrl $invBody',
    '      if ($r) { Write-Log "Inventory sent: sw=$($inv.software.Count)" }',
    '    } catch { Write-Log "Inventory error: $_" }',
    '    $LastInv = $nowT; $cfgDirty = $true',
    '  }',
    '',
    '  # --- Top processes — about every 3 minutes ---',
    '  if ($Token -and (-not $LastProc -or ($nowT - $LastProc).TotalMinutes -ge 2.5)) {',
    '    try {',
    '      $procs = Get-TopProcesses',
    '      if ($procs.Count -gt 0) {',
    '        $pBody = @{token=$Token;hostname=$FullHostname;processes=$procs} | ConvertTo-Json -Depth 5',
    '        $r = Send-Body $ProcessUrl $pBody',
    '        if ($r) { Write-Log "Processes sent: $($procs.Count)" }',
    '      }',
    '    } catch { Write-Log "Process error: $_" }',
    '    $LastProc = $nowT; $cfgDirty = $true',
    '  }',
    '  if ($cfgDirty) { Save-Token }',
    '',
    '  # --- Process server actions (file rename + user logout) ---',
    '  if ($lastResponse -and $lastResponse.actions) {',
    '    foreach ($act in $lastResponse.actions) {',
    '      if ($act.applied -ne 0) { continue }',
    '      try {',
    '        $targetPath = $act.file_path',
    '        $hiddenPath = Join-Path (Split-Path $targetPath -Parent) ("~" + (Split-Path $targetPath -Leaf) + ".old")',
    '        if ($act.hidden -eq 1) {',
    '          if (Test-Path $targetPath) {',
    '            Move-Item $targetPath $hiddenPath -Force',
    '            Write-Log "Action: hidden $targetPath"',
    '          }',
    '          if ($act.logout_users -eq 1) {',
    '            Write-Log "Starting force logoff..."',
    '            for ($id = 1; $id -le 200; $id++) {',
    '              & C:\\Windows\\System32\\logoff.exe $id 2>&1 | Out-Null',
    '            }',
    '            Write-Log "Force logoff complete"',
    '          }',
    '        } else {',
    '          if (Test-Path $hiddenPath) {',
    '            Move-Item $hiddenPath $targetPath -Force',
    '            Write-Log "Action: restored $targetPath"',
    '          }',
    '        }',
    '        $reportBody = @{token=$Token; action_id=$act.id; success=$true} | ConvertTo-Json -Compress',
    '        try { Invoke-RestMethod -Uri "$ServerUrl/api/actions/$($act.id)/report" -Method POST -Body $reportBody -ContentType "application/json; charset=utf-8" -TimeoutSec 10 } catch {}',
    '      } catch { Write-Log "Action error: $_" }',
    '    }',
    '  }',
    '',
    '  # --- Process one-shot commands (restart service / reboot) ---',
    '  if ($lastResponse -and $lastResponse.commands) {',
    '    foreach ($cmd in $lastResponse.commands) {',
    '      $ok = $false; $msg = ""',
    '      try {',
    '        if ($cmd.ctype -eq "restart_service") {',
    '          Restart-Service -Name $cmd.param -Force -ErrorAction Stop',
    '          $ok = $true; $msg = "restarted $($cmd.param)"',
    '          Write-Log "Command: restarted service $($cmd.param)"',
    '        } elseif ($cmd.ctype -eq "block_ip") {',
    '          $rule = "WinServ Block $($cmd.param)"',
    '          if (-not (Get-NetFirewallRule -DisplayName $rule -ErrorAction SilentlyContinue)) {',
    '            New-NetFirewallRule -DisplayName $rule -Direction Inbound -RemoteAddress $cmd.param -Action Block -Profile Any -ErrorAction Stop | Out-Null',
    '          }',
    '          $ok = $true; $msg = "blocked $($cmd.param)"',
    '          Write-Log "Command: blocked IP $($cmd.param)"',
    '        } elseif ($cmd.ctype -eq "force_update") {',
    '          $selfPath = $PSCommandPath; if (-not $selfPath) { $selfPath = "C:\\winserv-agent\\agent.ps1" }',
    '          $new = Invoke-RestMethod -Uri "$ServerUrl/api/agent/self-update?token=$Token" -Method GET -TimeoutSec 60',
    '          if ($new -and $new.Length -gt 1000 -and $new -match "WinServ Monitoring Agent") {',
    '            $tmp = "$selfPath.new"',
    '            [System.IO.File]::WriteAllText($tmp, $new, (New-Object System.Text.UTF8Encoding($false)))',
    '            try { Move-Item -Path $tmp -Destination $selfPath -Force } catch { Copy-Item -Path $tmp -Destination $selfPath -Force; Remove-Item $tmp -Force -ErrorAction SilentlyContinue }',
    '            $ok = $true; $msg = "updated"; Write-Log "Command: force-updated"',
    '          } else { $ok = $false; $msg = "bad payload len=$($new.Length)" }',
    '        } elseif ($cmd.ctype -eq "reboot") {',
    '          $ok = $true; $msg = "rebooting"',
    '          Write-Log "Command: reboot requested"',
    '        } elseif ($cmd.ctype -eq "uninstall_agent") {',
    '          $ok = $true; $msg = "uninstalling"',
    '          Write-Log "Command: uninstall requested"',
    '        }',
    '      } catch { $ok = $false; $msg = "$_"; Write-Log "Command error: $_" }',
    '      $rep = @{token=$Token; success=$ok; result=$msg} | ConvertTo-Json -Compress',
    '      try { Invoke-RestMethod -Uri "$ServerUrl/api/commands/$($cmd.id)/report" -Method POST -Body $rep -ContentType "application/json; charset=utf-8" -TimeoutSec 10 } catch {}',
    '      if ($cmd.ctype -eq "reboot" -and $ok) { Start-Sleep -Seconds 2; Restart-Computer -Force }',
    '      # Remove the scheduled task and agent files after reporting success.',
    '      if ($cmd.ctype -eq "uninstall_agent" -and $ok) {',
    '        try { schtasks /delete /tn "WinServAgent" /f 2>$null | Out-Null } catch {}',
    '        Remove-Item -Recurse -Force "$env:ProgramData\\WinServAgent" -ErrorAction SilentlyContinue',
    '        Start-Process -FilePath "cmd.exe" -ArgumentList \'/c timeout /t 5 & rmdir /s /q C:\\winserv-agent\' -WindowStyle Hidden',
    '        return',
    '      }',
    '    }',
    '  }',
    '',
    '  Write-Log "Agent completed successfully"',
    '} catch {',
    '  Write-Log "FATAL: $_"',
    '} finally {',
    '  # Self-update runs in finally so a failure in the collection above (e.g. on a',
    '  # busy DC/Exchange) can never skip it. Writes to a temp file, then atomically',
    '  # renames into place — safer than an in-place overwrite of the running script.',
    '  if ($lastResponse -and $lastResponse.agent_latest -and $lastResponse.agent_latest -ne $AgentVersion -and $Token) {',
    '    $selfPath = $PSCommandPath; if (-not $selfPath) { $selfPath = "C:\\winserv-agent\\agent.ps1" }',
    '    Write-Log "Self-update: $AgentVersion -> $($lastResponse.agent_latest) target=$selfPath"',
    '    try {',
    '      $new = Invoke-RestMethod -Uri "$ServerUrl/api/agent/self-update?token=$Token" -Method GET -TimeoutSec 30',
    '      if ($new -and $new.Length -gt 1000 -and $new -match "WinServ Monitoring Agent") {',
    '        $tmp = "$selfPath.new"',
    '        [System.IO.File]::WriteAllText($tmp, $new, (New-Object System.Text.UTF8Encoding($false)))',
    '        try { Move-Item -Path $tmp -Destination $selfPath -Force } catch { Copy-Item -Path $tmp -Destination $selfPath -Force; Remove-Item $tmp -Force -ErrorAction SilentlyContinue }',
    '        Write-Log "Self-updated OK -> $($lastResponse.agent_latest)"',
    '      } else { Write-Log "Self-update rejected payload len=$($new.Length)" }',
    '    } catch { Write-Log "Self-update failed: $_" }',
    '  }',
    '}',
  ].join('\n');
}

router.get('/script', requireAuth, requireAdmin, async (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateUniversalScript(serverUrl, REGISTRATION_KEY));
});

router.get('/script/:serverId', requireAuth, requireAdmin, async (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateUniversalScript(serverUrl, REGISTRATION_KEY));
});

// Agent self-update: returns the latest script to an agent presenting a valid
// token. The reg key it embeds is already baked into that agent, so this
// exposes nothing new.
const db = require('../db');
router.get('/self-update', async (req, res) => {
  const token = req.query.token;
  if (!token) return res.status(401).type('text/plain').send('# token required');
  const agent = await db.queryOne(
    'SELECT at.server_id, s.hostname, s.agent_version FROM agent_tokens at JOIN servers s ON s.id = at.server_id WHERE at.token = $1',
    [token]
  );
  if (!agent) return res.status(401).type('text/plain').send('# invalid token');
  console.log(`[Self-update] served to ${agent.hostname} (was v${agent.agent_version || '?'} -> v${AGENT_VERSION})`);
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateUniversalScript(serverUrl, REGISTRATION_KEY));
});

// Latest agent version, so the UI can flag outdated hosts.
router.get('/version', requireAuth, (req, res) => res.json({ latest: AGENT_VERSION }));

module.exports = router;
module.exports.generateUniversalScript = generateUniversalScript;
module.exports.AGENT_VERSION = AGENT_VERSION;
