const express = require('express');
const { requireAuth, requireAdmin } = require('../middleware/authMiddleware');
const { generateUniversalScript } = require('./agent');

const router = express.Router();
const REGISTRATION_KEY = process.env.REGISTRATION_KEY || 'winserv-reg-key-change-me';

function generateDeployerScript(serverUrl, regKey) {
  const agentPs = generateUniversalScript(serverUrl, regKey);
  const agentB64 = Buffer.from(agentPs, 'utf-8').toString('base64');

  return [
    '# WinServ Monitoring — Mass Deployer v2.2',
    '# ====================================================================',
    '# Run on a domain-joined machine with Domain Admin rights.',
    '# Discovers servers, select with checkboxes, remote installs agent.',
    '# ====================================================================',
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$ErrorActionPreference = "Continue"',
    '$ServerUrl = "' + serverUrl + '"',
    '',
    '$AgentB64 = "' + agentB64 + '"',
    '$AgentScript = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($AgentB64))',
    '',
    'function Get-DomainServers {',
    '  param($Domain)',
    '  Import-Module ActiveDirectory -ErrorAction Stop',
    '  if ($Domain) {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Server $Domain -Properties OperatingSystem,DNSHostName',
    '  } else {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Properties OperatingSystem,DNSHostName',
    '  }',
    '}',
    '',
    'function Install-Agent {',
    '  param($ComputerName)',
    '  try { $ping = Test-Connection -ComputerName $ComputerName -Count 1 -Quiet -ErrorAction Stop } catch { return "OFFLINE" }',
    '  if (-not $ping) { return "OFFLINE" }',
    '  try {',
    '    $remotePath = "\\\\$ComputerName\\C$\\winserv-agent"',
    '    if (-not (Test-Path $remotePath)) { New-Item -ItemType Directory -Path $remotePath -Force | Out-Null }',
    '    $AgentScript | Set-Content -Path "$remotePath\\agent.ps1" -Encoding UTF8 -Force',
    '    $cmd = "@echo off`r`nC:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File `"C:\\winserv-agent\\agent.ps1`""',
    '    $cmd | Set-Content -Path "$remotePath\\run.cmd" -Encoding ASCII -Force',
    '    schtasks /delete /tn "WinServAgent" /s $ComputerName /f 2>$null',
    '    schtasks /create /tn "WinServAgent" /s $ComputerName /ru "NT AUTHORITY\\SYSTEM" /rl HIGHEST /sc minute /mo 1 /tr "C:\\winserv-agent\\run.cmd" /f',
    '    return "OK"',
    '  } catch { return "ERROR: $_" }',
    '}',
    '',
    'function Get-RemoteVersion {',
    '  param($ComputerName)',
    '  try {',
    '    $c = Get-Content "\\\\$ComputerName\\C$\\winserv-agent\\agent.ps1" -Raw -ErrorAction Stop',
    '    if ($c -match \'Agent v([0-9.]+)\') { return $matches[1] }',
    '    return "unknown"',
    '  } catch { return $null }',
    '}',
    '',
    'Clear-Host',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host " WinServ Mass Deployer v2.2" -ForegroundColor Cyan',
    'Write-Host " Server: $ServerUrl" -ForegroundColor Cyan',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host ""',
    '',
    '$domain = $null; $domainInput = Read-Host "Enter domain name (or Enter for current domain)"',
    'if ($domainInput) { $domain = $domainInput } else { try { $domain = (Get-ADDomain).DNSRoot } catch {} }',
    '',
    'Write-Host "Discovering servers in domain: $domain ..." -ForegroundColor Yellow',
    'try {',
    '  $allServers = Get-DomainServers -Domain $domain | Select-Object Name, DNSHostName, OperatingSystem',
    '  Write-Host "Found $($allServers.Count) servers" -ForegroundColor Green',
    '} catch {',
    '  Write-Host "ActiveDirectory module not available!" -ForegroundColor Red',
    '  Write-Host "On a DC: Import-Module ActiveDirectory" -ForegroundColor Yellow',
    '  Write-Host "On Win10/11: Install-WindowsFeature RSAT-AD-PowerShell" -ForegroundColor Yellow',
    '  exit 1',
    '}',
    '',
    'if ($allServers.Count -eq 0) { Write-Host "No servers found." -ForegroundColor Red; exit 1 }',
    '',
    '$serverList = @()',
    '$checked = @{}',
    'for ($i=0; $i -lt $allServers.Count; $i++) {',
    '  $s = $allServers[$i]',
    '  $h = if ($s.DNSHostName) { $s.DNSHostName } else { $s.Name }',
    '  $checked["$i"] = $true',
    '  $serverList += @{idx=$i; hostname=$h; name=$s.Name; os=$s.OperatingSystem}',
    '}',
    '',
    'function Show-Menu {',
    '  Clear-Host',
    '  Write-Host "========================================" -ForegroundColor Cyan',
    '  Write-Host " Select servers for agent installation" -ForegroundColor Cyan',
    '  Write-Host " [A] All  [N] None  [D] Deploy  [Q] Quit" -ForegroundColor Cyan',
    '  Write-Host "========================================" -ForegroundColor Cyan',
    '  Write-Host ""',
    '  foreach ($s in $serverList) {',
    '    $mark = if ($checked["$($s.idx)"]) { "[x]" } else { "[ ]" }',
    '    $num = "{0:D2}" -f ($s.idx + 1)',
    '    Write-Host ("  " + $mark + " " + $num + [char]9 + $s.hostname) -NoNewline',
    '    Write-Host ([char]9 + $s.os) -ForegroundColor DarkGray',
    '  }',
    '  Write-Host ""',
    '  Write-Host "Enter number to toggle, or command letter: " -NoNewline',
    '}',
    '',
    'do {',
    '  Show-Menu',
    '  $key = Read-Host',
    '  if ($key -eq "Q") { exit 0 }',
    '  if ($key -eq "A") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $true } }',
    '  if ($key -eq "N") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $false } }',
    '  if ($key -match \'^\\d+$\') {',
    '    $num = [int]$key - 1',
    '    if ($num -ge 0 -and $num -lt $serverList.Count) {',
    '      $checked["$num"] = -not $checked["$num"]',
    '    }',
    '  }',
    '} while ($key -ne "D")',
    '',
    '$selected = $serverList | Where-Object { $checked["$($_.idx)"] }',
    'if ($selected.Count -eq 0) { Write-Host "No servers selected."; exit 0 }',
    '',
    'Write-Host ""; Write-Host "Deploying to $($selected.Count) servers..." -ForegroundColor Yellow',
    '$results = @(); $i = 1',
    '',
    'foreach ($srv in $selected) {',
    '  $h = $srv.hostname',
    '  Write-Host "  [$i/$($selected.Count)] $h " -NoNewline',
    '  $ex = Get-RemoteVersion -ComputerName $h',
    '  if ($ex) { Write-Host "(v$ex) " -NoNewline }',
    '  $r = Install-Agent -ComputerName $h',
    '  if ($r -eq "OK") { Write-Host "INSTALLED" -ForegroundColor Green }',
    '  elseif ($r -eq "OFFLINE") { Write-Host "OFFLINE" -ForegroundColor Red }',
    '  else { Write-Host $r -ForegroundColor Red }',
    '  $results += @{hostname=$h;result=$r}; $i++',
    '}',
    '',
    'Write-Host ""',
    'Write-Host "================================" -ForegroundColor Cyan',
    'Write-Host " DEPLOYMENT COMPLETE" -ForegroundColor Cyan',
    'Write-Host "================================" -ForegroundColor Cyan',
    'Write-Host (" Installed: " + ($results|?{$_.result -eq "OK"}).Count + "  Offline: " + ($results|?{$_.result -eq "OFFLINE"}).Count + "  Errors: " + ($results|?{$_.result -match "ERROR"}).Count)',
    'Write-Host "Servers appear in dashboard within 1-2 minutes." -ForegroundColor Yellow',
  ].join('\n');
}

router.get('/script', requireAuth, requireAdmin, (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateDeployerScript(serverUrl, REGISTRATION_KEY));
});

module.exports = router;
