const express = require('express');
const { requireAuth, requireAdmin } = require('../middleware/authMiddleware');
const { generateUniversalScript } = require('./agent');

const router = express.Router();
const REGISTRATION_KEY = process.env.REGISTRATION_KEY || 'winserv-reg-key-change-me';

function generateDeployerScript(serverUrl, regKey) {
  const agentPs = generateUniversalScript(serverUrl, regKey);
  const agentB64 = Buffer.from(agentPs, 'utf-8').toString('base64');

  return [
    '# WinServ Monitoring — Mass Deployer v2.3',
    '# ====================================================================',
    '# Run on a domain-joined machine with Domain Admin rights.',
    '# Discovers servers, select with checkboxes, remote installs agent.',
    '# ====================================================================',
    '# Self-elevate to admin (relaunch with UAC) and unblock itself, so there is',
    '# no manual "Run as administrator" or Unblock-File step.',
    'if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {',
    '  try { Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" } catch { Write-Host "Elevation cancelled." -ForegroundColor Red; Start-Sleep 3 }',
    '  exit',
    '}',
    'try { Unblock-File -Path $PSCommandPath -ErrorAction SilentlyContinue } catch {}',
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$ErrorActionPreference = "Continue"',
    '$ServerUrl = "' + serverUrl + '"',
    '',
    '$AgentB64 = "' + agentB64 + '"',
    '$AgentScript = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($AgentB64))',
    '',
    'function Get-DomainServers {',
    '  param($Domain)',
    '  Import-Module ActiveDirectory -ErrorAction Stop',
    '  if ($Domain) {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Server $Domain -Properties OperatingSystem,DNSHostName',
    '  } else {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Properties OperatingSystem,DNSHostName',
    '  }',
    '}',
    '',
    'function Install-Agent {',
    '  param($ComputerName)',
    '  # No ICMP gate: hardened hosts (e.g. terminal servers) often block ping',
    '  # yet are fully reachable over SMB (445) + WinRM (5985). Attempt the real',
    '  # operations and report the actual error, classifying genuine unreachable.',
    '  try {',
    '    $remotePath = "\\\\$ComputerName\\C$\\winserv-agent"',
    '    if (-not (Test-Path $remotePath)) { New-Item -ItemType Directory -Path $remotePath -Force -ErrorAction Stop | Out-Null }',
    '    [System.IO.File]::WriteAllText("$remotePath\\agent.ps1", $AgentScript, [System.Text.Encoding]::UTF8)',
    '    $taskSb = {',
    '      param($iv)',
    '      schtasks /delete /tn "WinServAgent" /f 2>$null',
    '      schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $iv /tr "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1" /f',
    '    }',
    '    Invoke-Command -ComputerName $ComputerName -ScriptBlock $taskSb -ArgumentList $script:IntervalMinutes -ErrorAction Stop',
    '    return "OK"',
    '  } catch {',
    '    $errMsg = $_.Exception.Message',
    '    if ($errMsg -match \'network path was not found|not accessible|unreachable|cannot find the (path|network)|timed out\') { return "OFFLINE (SMB 445?)" }',
    '    if ($errMsg -match \'WinRM|WS-Management|Enable-PSRemoting|cannot complete\') { return "ERROR: WinRM off/blocked (enable PSRemoting + open 5985): $errMsg" }',
    '    if ($errMsg -match \'Access is denied|denied\') { return "ERROR: access denied (need local-admin rights on target)" }',
    '    if ($errMsg.Length -gt 160) { $errMsg = $errMsg.Substring(0, 160) + "..." }',
    '    return "ERROR: $errMsg"',
    '  }',
    '}',
    '',
    'function Get-RemoteVersion {',
    '  param($ComputerName)',
    '  try {',
    '    $c = Get-Content "\\\\$ComputerName\\C$\\winserv-agent\\agent.ps1" -Raw -ErrorAction Stop',
    '    if ($c -match \'Agent v([0-9.]+)\') { return $matches[1] }',
    '    return "unknown"',
    '  } catch { return $null }',
    '}',
    '',
    'Clear-Host',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host " WinServ Mass Deployer v2.4" -ForegroundColor Cyan',
    'Write-Host " Server: $ServerUrl" -ForegroundColor Cyan',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host ""',
    '',
    '$domain = $null; $domainInput = Read-Host "Enter domain name (or Enter for current domain)"',
    'if ($domainInput) { $domain = $domainInput } else { try { $domain = (Get-ADDomain).DNSRoot } catch {} }',
    '',
    '$intervalInput = Read-Host "Metric interval in minutes [1-1439] (Enter for 1)"',
    '$script:IntervalMinutes = 1',
    'if ($intervalInput -match \'^\\d+$\' -and [int]$intervalInput -ge 1 -and [int]$intervalInput -le 1439) { $script:IntervalMinutes = [int]$intervalInput }',
    'Write-Host "Metric interval: every $script:IntervalMinutes min" -ForegroundColor Green',
    '',
    '$manualMode = $false',
    'try {',
    '  Import-Module ActiveDirectory -ErrorAction Stop',
    '  Write-Host "Discovering servers in domain: $domain ..." -ForegroundColor Yellow',
    '  $allServers = Get-DomainServers -Domain $domain | Select-Object Name, DNSHostName, OperatingSystem',
    '  Write-Host "Found $($allServers.Count) servers" -ForegroundColor Green',
    '} catch {',
    '  Write-Host "ActiveDirectory module not available." -ForegroundColor Red',
    '  $choice = Read-Host "Enter server names/IPs manually? [Y] Yes  [Q] Quit"',
    '  if ($choice -ne "Y") { exit 0 }',
    '  $manualMode = $true',
    '  Write-Host "Enter server names or IPs, one per line. Empty line = done." -ForegroundColor Yellow',
    '  $allServers = @()',
    '  do {',
    '    $entry = Read-Host "Server"',
    '    if ($entry) {',
    '      $ping = Test-Connection -ComputerName $entry -Count 1 -Quiet -ErrorAction SilentlyContinue',
    '      $status = if ($ping) { "ONLINE" } else { "OFFLINE" }',
    '      Write-Host "  $entry - $status" -ForegroundColor $(if ($ping) { "Green" } else { "Red" })',
    '      $allServers += [PSCustomObject]@{Name=$entry; DNSHostName=$entry; OperatingSystem=""}',
    '    }',
    '  } while ($entry)',
    '}',
    '',
    'if ($allServers.Count -eq 0) { Write-Host "No servers." -ForegroundColor Red; exit 1 }',
    '',
    '$serverList = @()',
    '$checked = @{}',
    'for ($i=0; $i -lt $allServers.Count; $i++) {',
    '  $s = $allServers[$i]',
    '  $h = if ($s.DNSHostName) { $s.DNSHostName } else { $s.Name }',
    '  $checked["$i"] = $false',
    '  $serverList += @{idx=$i; hostname=$h; name=$s.Name; os=$s.OperatingSystem}',
    '}',
    '',
    'function Show-Menu {',
    '  Clear-Host',
    '  Write-Host "========================================"',
    '  Write-Host " Select servers for agent installation"',
    '  Write-Host " [A] All  [N] None  [D] Deploy  [Q] Quit"',
    '  Write-Host "========================================"',
    '  foreach ($s in $serverList) {',
    '    $mark = if ($checked["$($s.idx)"]) { "[x]" } else { "[ ]" }',
    '    $num = "{0:D2}" -f ($s.idx + 1)',
    '    Write-Host ("  " + $mark + " " + $num + " " + $s.hostname)',
    '  }',
    '  Write-Host "Enter number to toggle, or command letter:"',
    '}',
    '',
    'do {',
    '  Show-Menu',
    '  $key = Read-Host',
    '  if ($key -eq "Q") { exit 0 }',
    '  if ($key -eq "A") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $true } }',
    '  if ($key -eq "N") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $false } }',
    '  if ($key -match \'^\\d+$\') {',
    '    $num = [int]$key - 1',
    '    if ($num -ge 0 -and $num -lt $serverList.Count) {',
    '      $checked["$num"] = -not $checked["$num"]',
    '    }',
    '  }',
    '} while ($key -ne "D")',
    '',
    '$selected = $serverList | Where-Object { $checked["$($_.idx)"] }',
    'if ($selected.Count -eq 0) { Write-Host "No servers selected."; exit 0 }',
    '',
    'Write-Host ""; Write-Host "Deploying to $($selected.Count) servers..." -ForegroundColor Yellow',
    '$results = @(); $i = 1',
    '',
    'foreach ($srv in $selected) {',
    '  $h = $srv.hostname',
    '  $ex = Get-RemoteVersion -ComputerName $h',
    '  $v = if ($ex) { "(v$ex) " } else { "" }',
    '  $r = Install-Agent -ComputerName $h 2>$null',
    '  $status = if ($r -eq "OK") { "INSTALLED" } elseif ($r -match "OFFLINE") { $r } else { "[FAIL] $r" }',
    '  Write-Host "  [$i/$($selected.Count)] $h $v$status"',
    '  $results += @{hostname=$h;result=$r}; $i++',
    '}',
    '',
    'Write-Host ""',
    'Write-Host "================================ DEPLOYMENT COMPLETE ==============================="',
    'Write-Host (" Installed: " + ($results|?{$_.result -eq "OK"}).Count + "  Offline: " + ($results|?{$_.result -match "OFFLINE"}).Count + "  Errors: " + ($results|?{$_.result -match "ERROR"}).Count)',
    'Write-Host "Servers appear in dashboard within 1-2 minutes."',
  ].join('\n');
}

// A tiny double-click launcher: self-elevates and runs winserv-deployer.ps1
// (which must sit in the same folder) with ExecutionPolicy Bypass — no unblock,
// no manual "Run as administrator".
function generateLauncherCmd() {
  return [
    '@echo off',
    'title WinServ Deployer',
    'net session >nul 2>&1',
    'if %errorlevel% neq 0 (',
    '  echo Requesting administrator rights...',
    '  powershell -NoProfile -Command "Start-Process -FilePath \'%~f0\' -Verb RunAs"',
    '  exit /b',
    ')',
    'cd /d "%~dp0"',
    'if not exist "%~dp0winserv-deployer.ps1" (',
    '  echo winserv-deployer.ps1 not found next to this launcher. Download it from the panel into this folder.',
    '  pause & exit /b',
    ')',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0winserv-deployer.ps1"',
    'echo.',
    'pause',
  ].join('\r\n');
}

router.get('/script', requireAuth, requireAdmin, (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateDeployerScript(serverUrl, REGISTRATION_KEY));
});

router.get('/launcher', requireAuth, requireAdmin, (req, res) => {
  res.type('text/plain; charset=utf-8');
  res.send(generateLauncherCmd());
});

module.exports = router;
module.exports.generateDeployerScript = generateDeployerScript;
