const express = require('express');
const { requireAuth, requireAdmin } = require('../middleware/authMiddleware');
const { generateUniversalScript } = require('./agent');
const { requireUnrestricted } = require('../services/scopeService');

const router = express.Router();
const REGISTRATION_KEY = process.env.REGISTRATION_KEY || 'winserv-reg-key-change-me';

function generateDeployerScript(serverUrl, regKey) {
  const agentPs = generateUniversalScript(serverUrl, regKey, process.env.FALLBACK_URL || '');
  const agentB64 = Buffer.from(agentPs, 'utf-8').toString('base64');

  return [
    '# WinServ Monitoring — Mass Deployer v2.11',
    '# ====================================================================',
    '# Run on a domain-joined machine with Domain Admin rights.',
    '# Discovers servers, select with checkboxes, remote installs agent.',
    '# ====================================================================',
    '# Self-elevate to admin (relaunch with UAC) and unblock itself, so there is',
    '# no manual "Run as administrator" or Unblock-File step.',
    'if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {',
    '  try { Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" } catch { Write-Host "Elevation cancelled." -ForegroundColor Red; Start-Sleep 3 }',
    '  exit',
    '}',
    'try { Unblock-File -Path $PSCommandPath -ErrorAction SilentlyContinue } catch {}',
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$ErrorActionPreference = "Continue"',
    '$ServerUrl = "' + serverUrl + '"',
    '',
    '$AgentB64 = "' + agentB64 + '"',
    '$AgentScript = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($AgentB64))',
    '',
    'function Get-DomainServers {',
    '  param($Domain)',
    '  Import-Module ActiveDirectory -ErrorAction Stop',
    '  if ($Domain) {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Server $Domain -Properties OperatingSystem,DNSHostName',
    '  } else {',
    '    Get-ADComputer -Filter {OperatingSystem -like "*Server*" -and Enabled -eq $true} -Properties OperatingSystem,DNSHostName',
    '  }',
    '}',
    '',
    'function Test-IsLocal {',
    '  param($ComputerName)',
    '  if (-not $ComputerName) { return $false }',
    '  $n = "$ComputerName".Trim()',
    '  if (@(\'.\', \'localhost\', \'127.0.0.1\', \'::1\') -contains $n.ToLower()) { return $true }',
    '  if ($n.Split(\'.\')[0] -eq $env:COMPUTERNAME) { return $true }',
    '  return $false',
    '}',
    '',
    'function Get-RemotePSVersion {',
    '  param($ComputerName)',
    '  if (Test-IsLocal $ComputerName) { return "$($PSVersionTable.PSVersion)" }',
    '  # Read the installed PowerShell version over remote registry (RPC), so it',
    '  # works on hosts where WinRM is unavailable. Key 3 = PS 3.0+, key 1 = PS 2.0.',
    '  try {',
    '    $rk = [Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey(\'LocalMachine\', $ComputerName)',
    '    foreach ($n in @(\'3\', \'1\')) {',
    '      $k = $rk.OpenSubKey("SOFTWARE\\Microsoft\\PowerShell\\$n\\PowerShellEngine")',
    '      if ($k) { $pv = $k.GetValue(\'PowerShellVersion\'); if ($pv) { return [string]$pv } }',
    '    }',
    '  } catch {}',
    '  return $null',
    '}',
    '',
    'function Grant-Write($dir) {',
    '  # A locked agent directory cannot be written by an admin push, so ownership',
    '  # and a write ACE are reclaimed first. The agent re-locks on its next run.',
    '  #',
    '  # Takes the DIRECTORY, not a file, and is NOT gated on Test-Path. Once the',
    '  # folder is SYSTEM-only an administrator cannot even enumerate it, so',
    '  # Test-Path answers false and the previous version skipped the repair',
    '  # entirely - which is why a push failed with "Access is denied" on',
    '  # agent.ps1 instead of fixing it. Both commands are harmless no-ops on a',
    '  # first install where the path does not exist yet.',
    '  #',
    '  # Administrators by SID S-1-5-32-544: the group name is localised.',
    '  & takeown /f "$dir" /r /d Y /a 2>&1 | Out-Null',
    '  & icacls "$dir" /grant:r "*S-1-5-32-544:(OI)(CI)(F)" /t /c 2>&1 | Out-Null',
    '}',
    '',
    'function Install-Agent {',
    '  param($ComputerName)',
    '  $tr = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File C:\\winserv-agent\\agent.ps1"',
    '',
    '  # 0) This computer: install straight to disk and create the task locally.',
    '  #    Going through the admin share / WinRM against ourselves needs neither',
    '  #    to be enabled, and fails on off-domain workstations where they are not.',
    '  if (Test-IsLocal $ComputerName) {',
    '    try {',
    '      if (-not (Test-Path "C:\\winserv-agent")) { New-Item -ItemType Directory -Path "C:\\winserv-agent" -Force -ErrorAction Stop | Out-Null }',
    '      Grant-Write "C:\\winserv-agent"',
    '      [System.IO.File]::WriteAllText("C:\\winserv-agent\\agent.ps1", $AgentScript, [System.Text.Encoding]::UTF8)',
    '    } catch { return "ERROR: cannot write C:\\winserv-agent - $($_.Exception.Message)" }',
    '    # End any instance still running first. A wedged agent keeps the task in',
    '    # the Running state, and Task Scheduler will not start a second instance —',
    '    # so a freshly copied script would sit on disk and never execute.',
    '    schtasks /end /tn "WinServAgent" 2>&1 | Out-Null',
    '    schtasks /delete /tn "WinServAgent" /f 2>&1 | Out-Null',
    '    $o = schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $script:IntervalMinutes /tr $tr /f 2>&1',
    '    if ($LASTEXITCODE -ne 0) {',
    '      $o = schtasks /create /tn "WinServAgent" /ru SYSTEM /sc minute /mo $script:IntervalMinutes /tr $tr /f 2>&1',
    '      if ($LASTEXITCODE -ne 0) { return "ERROR: schtasks - " + ((($o | Out-String)) -replace \'\\s+\', \' \').Trim() }',
    '    }',
    '    schtasks /query /tn "WinServAgent" 2>&1 | Out-Null',
    '    if ($LASTEXITCODE -ne 0) { return "ERROR: task missing after create" }',
    '    $script:LimitNote = Set-AgentTaskLimit $null',
    '    return "OK"',
    '  }',
    '',
    '  # 1) Copy the agent over SMB. No ICMP gate: hardened hosts block ping but',
    '  #    are reachable over 445.',
    '  try {',
    '    $remotePath = "\\\\$ComputerName\\C$\\winserv-agent"',
    '    if (-not (Test-Path $remotePath)) { New-Item -ItemType Directory -Path $remotePath -Force -ErrorAction Stop | Out-Null }',
    '    Grant-Write "$remotePath"',
    '    [System.IO.File]::WriteAllText("$remotePath\\agent.ps1", $AgentScript, [System.Text.Encoding]::UTF8)',
    '  } catch {',
    '    $e = $_.Exception.Message',
    '    if ($e -match \'network path was not found|not accessible|unreachable|cannot find the (path|network)|timed out\') { return "OFFLINE (SMB 445?)" }',
    '    if ($e -match \'Access is denied|denied\') { return "ERROR: access denied (need local-admin rights on target)" }',
    '    if ($e.Length -gt 160) { $e = $e.Substring(0, 160) + "..." }',
    '    return "ERROR: copy failed - $e"',
    '  }',
    '',
    '  # 2) Create the scheduled task. schtasks is a native exe, so a failure does',
    '  #    NOT raise a PowerShell error - the exit code must be checked, or we',
    '  #    report success while no task exists (exactly what happened on 2008).',
    '  $errs = @(); $created = $false',
    '  try {',
    '    $res = Invoke-Command -ComputerName $ComputerName -ErrorAction Stop -ArgumentList $script:IntervalMinutes, $tr -ScriptBlock {',
    '      param($iv, $trCmd)',
    '      schtasks /end /tn "WinServAgent" 2>$null | Out-Null',
    '      schtasks /delete /tn "WinServAgent" /f 2>$null | Out-Null',
    '      $o = schtasks /create /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $iv /tr $trCmd /f 2>&1',
    '      New-Object PSObject -Property @{ code = $LASTEXITCODE; out = ($o | Out-String) }',
    '    }',
    '    if ($res.code -eq 0) { $created = $true } else { $errs += "WinRM/schtasks: " + (($res.out) -replace \'\\s+\', \' \').Trim() }',
    '  } catch { $errs += "WinRM: " + $_.Exception.Message }',
    '',
    '  # 3) Fallback: schtasks /s uses RPC (135/445) and needs no WinRM at all -',
    '  #    this is what makes legacy hosts (2003/2008) work.',
    '  if (-not $created) {',
    '    schtasks /end /s $ComputerName /tn "WinServAgent" 2>&1 | Out-Null',
    '    schtasks /delete /s $ComputerName /tn "WinServAgent" /f 2>&1 | Out-Null',
    '    $o = schtasks /create /s $ComputerName /tn "WinServAgent" /ru SYSTEM /rl HIGHEST /sc minute /mo $script:IntervalMinutes /tr $tr /f 2>&1',
    '    if ($LASTEXITCODE -eq 0) { $created = $true }',
    '    else {',
    '      # Older schtasks builds reject /rl HIGHEST - retry without it.',
    '      $o2 = schtasks /create /s $ComputerName /tn "WinServAgent" /ru SYSTEM /sc minute /mo $script:IntervalMinutes /tr $tr /f 2>&1',
    '      if ($LASTEXITCODE -eq 0) { $created = $true }',
    '      else { $errs += "RPC/schtasks: " + ((($o2 | Out-String)) -replace \'\\s+\', \' \').Trim() }',
    '    }',
    '  }',
    '  if (-not $created) { return "ERROR: task not created - " + ($errs -join \' | \') }',
    '',
    '  # 4) Verify the task actually exists before claiming success.',
    '  schtasks /query /s $ComputerName /tn "WinServAgent" 2>&1 | Out-Null',
    '  if ($LASTEXITCODE -ne 0) { return "ERROR: schtasks reported success but the task is missing" }',
    '  $script:LimitNote = Set-AgentTaskLimit $ComputerName',
    '  return "OK"',
    '}',
    '',
    'function Set-AgentTaskLimit($computer) {',
    '  # Cap how long a single agent run may take.',
    '  #',
    '  # schtasks creates tasks with ExecutionTimeLimit = PT72H, and Task Scheduler',
    '  # will not start a second instance while one is running. So one wedged run',
    '  # blocks every later tick for three days and the host reads OFFLINE while it',
    '  # is perfectly healthy - the long unexplained gaps on the avtostek hosts.',
    '  #',
    '  # Done here, once, at install time, and never from the agent itself. When',
    '  # the agent re-registered its own task on every run it passed logonType 3,',
    '  # which is TASK_LOGON_INTERACTIVE_TOKEN and not SERVICE_ACCOUNT: the task',
    '  # could then only start while somebody was logged on interactively, so four',
    '  # servers went silent and had to be recovered by hand over SMB. The',
    '  # principal is therefore passed explicitly, and the result is read back and',
    '  # rolled back if it is not exactly what was intended.',
    '  try {',
    '    $svc = New-Object -ComObject Schedule.Service',
    '    if ($computer) { $svc.Connect($computer) } else { $svc.Connect() }',
    '    $folder = $svc.GetFolder("\\")',
    '    $task = $folder.GetTask("WinServAgent")',
    '    $originalXml = $task.Xml',
    '    $def = $task.Definition',
    '    if ($def.Settings.ExecutionTimeLimit -eq "PT5M") { return "ok" }',
    '    $def.Settings.ExecutionTimeLimit = "PT5M"',
    '    # 4 = TASK_UPDATE, 5 = TASK_LOGON_SERVICE_ACCOUNT (NOT 3 - see above)',
    '    [void]$folder.RegisterTaskDefinition("WinServAgent", $def, 4, "SYSTEM", $null, 5)',
    '    $after = $folder.GetTask("WinServAgent")',
    '    $ad = $after.Definition',
    '    $good = ($ad.Settings.ExecutionTimeLimit -eq "PT5M") -and ($ad.Principal.LogonType -eq 5) -and $after.Enabled -and ($ad.Triggers.Count -ge 1)',
    '    if ($good) { return "ok" }',
    '    # A task that cannot start is far worse than one with no time limit.',
    '    try { [void]$folder.RegisterTask("WinServAgent", $originalXml, 4, "SYSTEM", $null, 5, $null) } catch {}',
    '    return "limit rolled back (logon=$($ad.Principal.LogonType) limit=$($ad.Settings.ExecutionTimeLimit))"',
    '  } catch { return "limit not set: $($_.Exception.Message)" }',
    '}',
    '',
    'function Get-RemoteVersion {',
    '  param($ComputerName)',
    '  try {',
    '    $p = if (Test-IsLocal $ComputerName) { "C:\\winserv-agent\\agent.ps1" } else { "\\\\$ComputerName\\C$\\winserv-agent\\agent.ps1" }',
    '    $c = Get-Content $p -Raw -ErrorAction Stop',
    '    if ($c -match \'Agent v([0-9.]+)\') { return $matches[1] }',
    '    return "unknown"',
    '  } catch { return $null }',
    '}',
    '',
    'Clear-Host',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host " WinServ Mass Deployer v2.11" -ForegroundColor Cyan',
    'Write-Host " Server: $ServerUrl" -ForegroundColor Cyan',
    'Write-Host "========================================" -ForegroundColor Cyan',
    'Write-Host ""',
    '',
    '$domain = $null; $domainInput = Read-Host "Enter domain name (or Enter for current domain)"',
    'if ($domainInput) { $domain = $domainInput } else { try { $domain = (Get-ADDomain).DNSRoot } catch {} }',
    '',
    '$intervalInput = Read-Host "Metric interval in minutes [1-1439] (Enter for 1)"',
    '$script:IntervalMinutes = 1',
    'if ($intervalInput -match \'^\\d+$\' -and [int]$intervalInput -ge 1 -and [int]$intervalInput -le 1439) { $script:IntervalMinutes = [int]$intervalInput }',
    'Write-Host "Metric interval: every $script:IntervalMinutes min" -ForegroundColor Green',
    '',
    '$allServers = @()',
    'try {',
    '  Import-Module ActiveDirectory -ErrorAction Stop',
    '  Write-Host "Discovering servers in domain: $domain ..." -ForegroundColor Yellow',
    '  $allServers = @(Get-DomainServers -Domain $domain | Select-Object Name, DNSHostName, OperatingSystem)',
    '  Write-Host "Found $($allServers.Count) domain servers" -ForegroundColor Green',
    '} catch {',
    '  Write-Host "ActiveDirectory module not available - listing this computer only." -ForegroundColor Yellow',
    '  Write-Host "Use [M] in the menu to add more machines by name or IP." -ForegroundColor Yellow',
    '}',
    '',
    '# Always offer the machine the deployer is running on. Off-domain stations',
    '# have no AD to enumerate, and this is usually exactly the host to install on.',
    '$LocalFqdn = try { [System.Net.Dns]::GetHostEntry(\'\').HostName } catch { $env:COMPUTERNAME }',
    'if (-not ($allServers | Where-Object { $_.Name -eq $env:COMPUTERNAME -or $_.DNSHostName -eq $LocalFqdn })) {',
    '  $allServers = @([PSCustomObject]@{Name=$env:COMPUTERNAME; DNSHostName=$LocalFqdn; OperatingSystem=\'(this computer)\'}) + $allServers',
    '}',
    '',
    'if ($allServers.Count -eq 0) { Write-Host "No machines." -ForegroundColor Red; exit 1 }',
    '',
    '$serverList = @()',
    '$checked = @{}',
    'for ($i=0; $i -lt $allServers.Count; $i++) {',
    '  $s = $allServers[$i]',
    '  $h = if ($s.DNSHostName) { $s.DNSHostName } else { $s.Name }',
    '  $checked["$i"] = $false',
    '  $serverList += @{idx=$i; hostname=$h; name=$s.Name; os=$s.OperatingSystem}',
    '}',
    '',
    'function Show-Menu {',
    '  Clear-Host',
    '  Write-Host "========================================"',
    '  Write-Host " Select machines for agent installation"',
    '  Write-Host " [A] All  [N] None  [M] Add by name/IP  [D] Deploy  [Q] Quit"',
    '  Write-Host "========================================"',
    '  foreach ($s in $serverList) {',
    '    $mark = if ($checked["$($s.idx)"]) { "[x]" } else { "[ ]" }',
    '    $num = "{0:D2}" -f ($s.idx + 1)',
    '    $tag = if (Test-IsLocal $s.hostname) { " (this computer)" } elseif ($s.os -eq "(manual)") { " (manual)" } else { "" }',
    '    Write-Host ("  " + $mark + " " + $num + " " + $s.hostname + $tag)',
    '  }',
    '  Write-Host "Enter number to toggle, or command letter:"',
    '}',
    '',
    'do {',
    '  Show-Menu',
    '  $key = Read-Host',
    '  if ($key -eq "Q") { exit 0 }',
    '  if ($key -eq "A") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $true } }',
    '  if ($key -eq "N") { foreach ($s in $serverList) { $checked["$($s.idx)"] = $false } }',
    '  if ($key -eq "M") {',
    '    $entry = Read-Host "Machine name or IP"',
    '    if ($entry) {',
    '      $newIdx = $serverList.Count',
    '      $serverList += @{idx=$newIdx; hostname=$entry.Trim(); name=$entry.Trim(); os="(manual)"}',
    '      $checked["$newIdx"] = $true',
    '    }',
    '  }',
    '  if ($key -match \'^\\d+$\') {',
    '    $num = [int]$key - 1',
    '    if ($num -ge 0 -and $num -lt $serverList.Count) {',
    '      $checked["$num"] = -not $checked["$num"]',
    '    }',
    '  }',
    '} while ($key -ne "D")',
    '',
    '# @() is required: with a single match the pipeline returns the hashtable',
    '# itself, and .Count on a hashtable is its NUMBER OF KEYS - which is why one',
    '# selected machine was announced as "Deploying to 4 servers".',
    '$selected = @($serverList | Where-Object { $checked["$($_.idx)"] })',
    'if ($selected.Count -eq 0) { Write-Host "No servers selected."; exit 0 }',
    '',
    'Write-Host ""; Write-Host "Deploying to $($selected.Count) servers..." -ForegroundColor Yellow',
    '$results = @(); $i = 1',
    '',
    'foreach ($srv in $selected) {',
    '  $h = $srv.hostname',
    '  $ex = Get-RemoteVersion -ComputerName $h',
    '  $v = if ($ex) { "(v$ex) " } else { "" }',
    '  $script:LimitNote = "ok"',
    '  $r = Install-Agent -ComputerName $h 2>$null',
    '  $status = if ($r -eq "OK") { "INSTALLED" } elseif ($r -match "OFFLINE") { $r } else { "[FAIL] $r" }',
    '  Write-Host "  [$i/$($selected.Count)] $h $v$status"',
    '  # The agent uses Get-CimInstance / ConvertTo-Json / Invoke-RestMethod, all of',
    '  # which need PowerShell 3.0+. On a stock 2008 SP2 (PS 2.0) the task would run',
    '  # and silently fail, so say so instead of leaving a dead install behind.',
    '  # Not fatal: the agent runs fine without the cap, it just means a wedged',
    '  # run can block the next tick for up to the schtasks default of 72 hours.',
    '  if ($r -eq "OK" -and $script:LimitNote -ne "ok") {',
    '    Write-Host "        ^ run time limit not applied: $script:LimitNote" -ForegroundColor Yellow',
    '  }',
    '  $psWarn = $false',
    '  if ($r -eq "OK") {',
    '    $psv = Get-RemotePSVersion -ComputerName $h',
    '    if ($psv) {',
    '      try { if ([version]$psv -lt [version]"3.0") { $psWarn = $true } } catch {}',
    '      if ($psWarn) { Write-Host "        ^ PowerShell $psv - agent needs 3.0+. Install WMF 3.0 (or newer) on this host, else it will never report." -ForegroundColor Yellow }',
    '    } else {',
    '      Write-Host "        ^ could not read PowerShell version (Remote Registry off). If this is Server 2003/2008, ensure WMF 3.0+ is installed." -ForegroundColor DarkYellow',
    '    }',
    '  }',
    '  $results += @{hostname=$h;result=$r;pswarn=$psWarn}; $i++',
    '}',
    '',
    'Write-Host ""',
    'Write-Host "================================ DEPLOYMENT COMPLETE ==============================="',
    'Write-Host (" Installed: " + @($results|?{$_.result -eq "OK"}).Count + "  Offline: " + @($results|?{$_.result -match "OFFLINE"}).Count + "  Errors: " + @($results|?{$_.result -match "ERROR"}).Count + "  Needs WMF 3.0: " + @($results|?{$_.pswarn}).Count)',
    'Write-Host "Servers appear in dashboard within 1-2 minutes."',
  ].join('\n');
}

// A tiny double-click launcher: self-elevates and runs winserv-deployer.ps1
// (which must sit in the same folder) with ExecutionPolicy Bypass — no unblock,
// no manual "Run as administrator".
function generateLauncherCmd() {
  return [
    '@echo off',
    'title WinServ Deployer',
    'net session >nul 2>&1',
    'if %errorlevel% neq 0 (',
    '  echo Requesting administrator rights...',
    '  powershell -NoProfile -Command "Start-Process -FilePath \'%~f0\' -Verb RunAs"',
    '  exit /b',
    ')',
    'cd /d "%~dp0"',
    'if not exist "%~dp0winserv-deployer.ps1" (',
    '  echo winserv-deployer.ps1 not found next to this launcher. Download it from the panel into this folder.',
    '  pause & exit /b',
    ')',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0winserv-deployer.ps1"',
    'echo.',
    'pause',
  ].join('\r\n');
}

router.get('/script', requireAuth, requireAdmin, requireUnrestricted, (req, res) => {
  const serverUrl = (process.env.PUBLIC_URL || 'http://localhost:' + (process.env.PORT || '3000')).replace(/\/$/, '');
  res.type('text/plain; charset=utf-8');
  res.send(generateDeployerScript(serverUrl, REGISTRATION_KEY));
});

router.get('/launcher', requireAuth, requireAdmin, requireUnrestricted, (req, res) => {
  res.type('text/plain; charset=utf-8');
  res.send(generateLauncherCmd());
});

module.exports = router;
module.exports.generateDeployerScript = generateDeployerScript;
